### ISSUE TITLE
Disconnecting immediately after publishing

### ISSUE THREAD

**Issue by stepanmracek** [sclausen/ngx-mqtt#100]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request

## Current behavior
When I disconnect from the MQTT broker immediately after the successful publishing, the message does not reach broker.

## Expected behavior
I would expect that If I disconnect from the broker like this:
```typescript
this.mqtt.publish('topic', 'message').subscribe({ complete: () => this.mqtt.disconnect() });
```
The message gets to other clients listening to the topic `topic`.

## Minimal reproduction of the problem with instructions

[Here](https://github.com/stepanmracek/ngx-mqtt-disconnect-after-publish) is a repository that reproduce this issue. I'm listening to the broker from command line using `mosquitto_sub -t "topic"`. If you uncomment line 
38 in app.component.ts (delay operator), the second message reach the broker and all other clients.

## Environment
<pre><code>ngx-mqtt version: 6.3.1
Broker: Mosquitto</code></pre>

**Comment by sclausen** [comment]
I'm so happy that your issues are always well formed and with a proper reproduction :relieved: 

Let's see what I can find out.

**Comment by sclausen** [comment]
You simply have to pass `false` to `disconnect` for disconnecting gracefully. Then the message will go through.
Did this worked for you?

**Comment by stepanmracek** [comment]
Yes, thanks. It helped. I just tested that also increasing QoS to 1 or to 2 will help, which make probably more sense, since this gives you guarantee that the message will be delivered to the broker. You can close this issue.
