### ISSUE TITLE
[Feature request] make publish() pipeable

### ISSUE THREAD

**Issue by stepanmracek** [sclausen/ngx-mqtt#101]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior
The method `MqttService.publish(topic: string, message: any, options?: IPublishOptions): Observable<void>` never returns a value (just completes or throws an error). This makes it difficult to pipe actions in `Observable.pipe()`

## Expected behavior
It would be nice to do something like this:
```typescript
this.mqtt.onConnect.pipe(
  concatMap(() => mqtt.publish('topic', 'first')),
  delay(1000),
  concatMap(() => mqtt.publish('topic', 'second')),
).subscribe(() => {
  this.mqtt.disconnect();
});
```

## What is the motivation / use case for changing the behavior?
Now, if you want to do something like this, you have to wrap `mqtt.publish()` method and return custom observable:
```typescript
pipeablePublish(topic: string, message: any): Observable<void> {
  return new Observable<void>(observer => {
    this.mqtt.publish(topic, message).subscribe({
      complete: () => {
        observer.next();
        observer.complete();
      }, error: error => {
        observer.error(error);
      }
    });
  });
}
```

## Environment
<pre><code>ngx-mqtt version: 6.3.1</code></pre>

**Comment by sclausen** [comment]
That's indeed an interesting feature. It seems that you already implemented most of it. Do you want to add a pull request, or are still features of this usecase missing you want me to develop?

**Comment by stepanmracek** [comment]
I can ad PR. The question is if you want to just extend existing publish() method. In this case the result is
```diff
@@ -220,6 +220,7 @@ export class MqttService {
         if (err) {
           obs.error(err);
         } else {
+          obs.next();
           obs.complete();
         }
       });```

Or you do not want to change behavior of existing function and rather make a new method that wraps `publish()` and emits value by calling `obs.next()` when publish completes.

**Comment by stepanmracek** [comment]
The existing behavior would stay the same, `mqtt.publish('topic', 'msg')).subscribe({complete: () => {...}});` will still work. Moreover, you will be able to write just `mqtt.publish('topic', 'msg')).subscribe(() => {...});` or use publish inside `Observable.pipe()`.
I will create PR later in the afternoon.

**Comment by sclausen** [comment]
Greaty :+1: That's a really nice addition!

**Comment by sclausen** [comment]
Thanks for the PR. I'll make a new release this evening
