### ISSUE TITLE
get current instance IONIC 3

### ISSUE THREAD

**Issue by teshtek** [sclausen/ngx-mqtt#103]
- [x ] **I have searched for similar issues in this repository, but couldn't find one.**
- [x ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Expected behavior

My subscribe have to update select fields and other things, but not on my device, only on the other clients that are in subscribe. Is there a way to capture my instance?

## Environment

<pre><code>
ngx-mqtt version: X.Y.Z

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
I don't think im sure, what you want to achieve. Could you please elaborate your usecase a bit mor detailed?

**Comment by sclausen** [comment]
Weird request, no further explanation -> Closed
