### ISSUE TITLE
Connect with ThingSpeak

### ISSUE THREAD

**Issue by maykon-oliveira** [sclausen/ngx-mqtt#104]
- [x] **I have read the README and have a basic understanding how angular works.**
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior

I can't connect with ThinkSpeak broker.

## Expected behavior

I would like to connect with ThinkSpeak broker.

## What is the motivation / use case for changing the behavior?

Many programmers use ThingSpeak for IoT, and this library does not support it. Me, for example.

## Environment

<pre><code>
ngx-mqtt version: 6.3.1

- Broker ThingSpeak

**Comment by sclausen** [comment]
Could you explain, why `ngx-mqtt` doesn't support ThingSpeak?
Are you [able to do with plain mqtt.js in the browser](https://sclausen.github.io/ngx-mqtt/#important-note) what you want to do with `ngx-mqtt`?

**Comment by maykon-oliveira** [comment]
Yes, I will show you. Let me write a code like example.

**Comment by bayaabid** [comment]
hostname: 'localhost',
  port: 15672,
  path: '/',
  password: 'guest',
  username: 'guest',

I'm using Rabbitmq
And I get this errors on the console
WebSocket connection to 'ws://localhost:15672/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by maykon-oliveira** [comment]
Here is the code [mqtt-test](https://github.com/maykon-oliveira/mqtt-test).

> Are you able to do with plain mqtt.js in the browser what you want to do with ngx-mqtt?

In this project has two file (sub.js, pub.js) in the root directory, that work perfectly with mqtt.js.

> Could you explain, why `ngx-mqtt` doesn't support ThingSpeak?

But in the ngx-mqtt-test component is the same implementation using ngx-mqtt, and don't work. I done anything wrong?

**Comment by sclausen** [comment]
@bayaabid would you be so kind and open a separate issue for a separate problem? Maybe reading the docs will help too https://www.rabbitmq.com/web-mqtt.html

**Comment by sclausen** [comment]
@maykon-oliveira how do you execute pub.js and sub.js?

**Comment by sclausen** [comment]
I explicitly asked you if you can do this with mqtt.js **in the browser**, not nodejs. You even quoted my question. 
After reading your code, I see you try to connect on port 1883 with your broker. That's the standard mqtt via tcp port for mosquitto.Thats a steong indicator, that you havent read the [manual](https://sclausen.github.io/ngx-mqtt/), especially the part about websockets. You can't communicate between the browser and the broker via mqtt over tcp, but only via mqtt over websockets.

**Comment by maykon-oliveira** [comment]
You're right, I didn't know that is no possible communicate between the browser and the broker via mqtt on tcp, but only via mqtt over websockets. Thanks a lot! 👍.

**Comment by sclausen** [comment]
You're welcome.
