### ISSUE TITLE
unable to unsubscribe mqtt using MqttService observe inside combinelatest

### ISSUE THREAD

**Issue by dario-frongillo** [sclausen/ngx-mqtt#107]
Hi All,
if i done only one  subscription inside a combinelatest ( so there arent other subscribtion):
`const subscription =  combinelatest(`this._mqttService.observe(TOPIC_A),  b).subscribe(()=>);`

and i execute unsubscribe on subscription 
`subscription .unsubscribe()`
ngx-mqtt not unsubscribe mqtt subscription on TOPIC_A.
Can you kindly please investigate ?
thanks and congratulation for the great works .. i really like this lib :)

**Comment by sclausen** [comment]
Please fill out the issue template.
