### ISSUE TITLE
Qos option in observe() function

### ISSUE THREAD

**Issue by teshtek** [sclausen/ngx-mqtt#108]
- [x ] **I have searched for similar issues in this repository, but couldn't find one.**
- [x ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x ] Feature request

## Expected behavior

I really need this implementation: adding options with qos on observe() function.

## What is the motivation / use case for changing the behavior?

I need to put qos to 1 or 2

## Environment

<pre><code>
"ngx-mqtt": "^6.3.1",

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
You should use the latest version `6.4.1`. `observe` and `observeRetained` can have `IClientSubscribeOptions` up from that version.
