### ISSUE TITLE
Publish works first time and next time it fails until reconnect

### ISSUE THREAD

**Issue by aparna999** [sclausen/ngx-mqtt#109]
## Current behavior
When I publish a topic for the first time, broker receives it but when I publish again with another topic it does nothing.
Basically, I can't publish again unless the connection closes and reconnects. I have a service in my application which in turn creates the MQTTService of ngx-mqtt instance and publishes to the broker. From my component, I call the publish method below, using the instance of mymqttservice.

mymqttservice.service.ts

publish(topic: string, message: string) {
    return this._mqttService.publish(topic, message, {qos: 1, retain: true}).subscribe();
}

Caller ->   this.publishObs = this.mymqttservice.publish(topic, '');

where publishObs is a Subscription and 
topic changes according to user interaction
message is empty

Same is the behavior with unsafePublish too.

## Expected behavior

I should be able to Publish many times untill the view is active. Moreover, I don't want to close the connection after a set of time. How can I make the connection be alive without closing and reconnecting because the user needs to be able to publish until he closes the view. It is when I want to disconnect. Automatic closing and reconnecting induces some lag.

## Environment

ngx-mqtt version: 5.4.0
angular 5

- Broker 
CloudMQTT

**Comment by sclausen** [comment]
Thabks for your issue. Please provide a proper reproduction as a repository.

**Comment by sclausen** [comment]
It's not that I'm too stupid to implement your snippet in an angular application, but it's time consuming and since this is a spare time project and you want me to help you, I ask you to help me with it.

**Comment by aparna999** [comment]
I'm sorry about that. I'm new to creating git repos. But I will try to make one soon. I hope, I can do it in StackBlitz.

**Comment by sclausen** [comment]
Another easy option would be the awesome angular-cli project.

**Comment by aparna999** [comment]
https://stackblitz.com/edit/angular-2xnwi4

I apologize, for not providing an MQTT connection credentials(since I cannot provide my employer's mqtt broker credentials, i created an instance in CloudMqtt for testing but was unable to connect) but this is what I was trying to do. 
When the component loads I connect to the broker and subscribe to device status. On button clicks I publish to run or stop device. So, which button we click first publishes correctly but the second time publish on button click doesn't publish the topic in the broker. When I wait for a while, I guess the connection will be closed and reconnected, it is when I can publish again.

**Comment by sclausen** [comment]
Would you be so kind and try [my fork of your app](https://stackblitz.com/edit/angular-f2rurj) with a little debugging? Can you tell me what you see in your browser console?
I see you use an empty topic. That's invalid by specification and should not work:
> All Topic Names and Topic Filters MUST be at least one character long [MQTT-4.7.3-1]

**Comment by aparna999** [comment]
Error: Connection refused: Not authorized
    at u._handleConnack (ngx-mqtt.min.js:7)
    at u._handlePacket (ngx-mqtt.min.js:7)
    at e (ngx-mqtt.min.js:7)
    at h.s._write (ngx-mqtt.min.js:7)
    at g (ngx-mqtt.min.js:7)
    at d (ngx-mqtt.min.js:7)
    at h.write (ngx-mqtt.min.js:7)
    at p.a (ngx-mqtt.min.js:7)
    at p.r.emit (ngx-mqtt.min.js:1)
    at h (ngx-mqtt.min.js:7)

preview-fe7237b13d780dbf847da.js:1 onClose

**Comment by sclausen** [comment]
Okay, that's before your empty topics who may be an issue nonetheless :smile: 
Does #20 help for the `Unauthorized` error?

**Comment by aparna999** [comment]
I was able to connect now. Here is the updated code. Please check.
https://stackblitz.com/edit/angular-g7p71r

Now you can notice the issue. 
Once, I click the run button, it publishes the topic on the broker.
Next, I clicked on the stop button, the topic is not received on the broker.
It happens in either way --> stop and then run.

I noticed that this issue happens when the message is empty.
I also see that in the console the connection is closed and then connected again. 
Why is it happening? How can I stay connected until the view is closed?

Broker login for u to check:
https://www.cloudmqtt.com/
username: aparna.pyla@gmail.com
pwd: irons123

**Comment by sclausen** [comment]
I didn't tried with your connection, but a simple mosquitto works very well. It seems you have some kind of backend configuration problem or you're not using the broker as it's devs intend to. E.g. some brokers do authentication via `clientId`.

I'm really sorry this all didn't worked for you, but since this isn't a problem with my library, but with your setup I can't help you.
