### ISSUE TITLE
ionic project failed to build after installing ngx-mqtt

### ISSUE THREAD

**Issue by dev008webO** [sclausen/ngx-mqtt#110]
I've just setup a new ionic app and after installing ngx-mqtt with `npm install ngx-mqtt@5.4.0 --save` it stopped building the project and says 
`typescript: node_modules/@types/node/index.d.ts`
`Subsequent variable declarations must have the same type. Variable 'process' must be of type '{ env: { [key: string]: string; }; }', but here has type 'Process'. 
L47:  declare function setImmediate(callback: (...args: any[]) => void, ...args: any[]): any;
L48:  declare function clearImmediate(immediateId: any): void;`.

Here is my package.json.

```
{
    "name": "dd",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "start": "ionic-app-scripts serve",
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.12.0",
    "@ionic-native/splash-screen": "~4.12.0",
    "@ionic-native/status-bar": "~4.12.0",
    "@ionic/storage": "2.1.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "ngx-mqtt": "^5.4.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project"
}
`

**Comment by sclausen** [comment]
Would you be so kind and follow the issue template!?

**Comment by dev008webO** [comment]
Here is the repo i've created. https://github.com/dev008webO/ionic-mqtt-demo.git. i've just made a new ionic project and installed ngx-mqtt by `npm install ngx-mqtt@5.4.0 --save`. and it giving this error at time of  `ionic serve.`

**Comment by sclausen** [comment]
The ionic project hast the same error in their examples, so I think this might be something on their side.
ionic-team/ionic-cli#3541
I'll keep this issue open, but won't work on it, since I wan't to wait how the referenced one develops.

**Comment by sclausen** [comment]
@dwieeb has a plausible explanation where this error may come from and I think we just have to wait until he resolves this issue.

**Comment by sclausen** [comment]
@dev008webO do the recent comments in the issue mentioned above help you?

**Comment by dev008webO** [comment]
It worked. Try the solution of @dwieeb from [https://github.com/ionic-team/ionic-cli/issues/3541](onic-team/ionic-cli#3541). Just deleted `src/declarations.d.ts` file from project. and it worked. Thank you so much @sclausen
