### ISSUE TITLE
support 'offline' event

### ISSUE THREAD

**Issue by tao-cumplido** [sclausen/ngx-mqtt#111]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**

- [ ] **I can run the plain mqtt.js example on https://sclausen.github.io/ngx-mqtt/ to connect, but it fails with ngx-mqtt.**

## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior

No access to `client.on('offline')`

## Expected behavior

Expose `client.on('offline')` the same way as other events.

## What is the motivation / use case for changing the behavior?

We use the `offline` event to track problems we are encountering with Mosquitto from time to time.

## Environment

<pre><code>
ngx-mqtt version: 6.4.1

- Mosquitto
</code></pre>

**Comment by sclausen** [comment]
Yeah, why not. I'll work something out.

**Comment by sclausen** [comment]
Isn't `onClose` what you need? It's the event that will be emitted, if the client disconnects.

**Comment by tao-cumplido** [comment]
Maybe you're right. I had been using the offline event when I was still trying to figure out how to use mqtt. I was just missing it when I ported the code base from Angular 5 to 6, where I had been using mqtt.js directly. After some trying it looks, like I don't actually need it any more.
If I ever find I do need it, I'll reopen.
Thanks!

**Comment by sclausen** [comment]
But don't you think the `onClose` event *is* the offline event, or do you mean something different?

**Comment by tao-cumplido** [comment]
No, `close` and `offline` are two different events on the mqtt.js client.
https://github.com/mqttjs/MQTT.js/#event-offline

**Comment by sclausen** [comment]
Yeah, you've got a point. This feature is now available in [6.5.1](https://github.com/sclausen/ngx-mqtt/releases/tag/6.5.1)
