### ISSUE TITLE
NGX-MQTT@5.4.0 with Ionic 3

### ISSUE THREAD

**Issue by nchanti** [sclausen/ngx-mqtt#114]
- [ X] **I have searched for similar issues in this repository, but couldn't find one.**
- [ X] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ X] Bug report  
- [ ] Feature request

## Current behavior

I am trying to implement the following GitHub:
https://github.com/praseedm/Mqtt_test
But I get the following error when I run "ionic serve"
Typescript Error: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated. Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.
src/pages/home/home.ts: Line 34)
this.subs = this.mqttService.observe(topic).subscribe(

## Expected behavior

App Connect and subscribe to mqtt broker

## Minimal reproduction of the problem with instructions

https://github.com/praseedm/Mqtt_test

## What is the motivation / use case for changing the behavior?

App Connect and subscribe to mqtt broker

## Environment
Ionic Framework: 3.9.2
Ionic App Scripts: 3.2.0
Angular Core: 5.2.11
Angular Compiler CLI: 5.2.11
Node: 8.11.4
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
<pre><code>
ngx-mqtt version: 5.4.3
rxjs@>=5.5.0
handlebars@^4.0.11
zone.js@~0.8.26

Cannot migrate to ngx-mqtt 6, because ionic 3 framework is using Angular Core: 5.2.11
- Broker 
Mosquito
Others:

I also tried the code on your webpage: https://sclausen.github.io/ngx-mqtt/ and got the following  error:
Property '_mqttService' does not exist on type 'SettingsPage'.
Line 15: this.subscription = this._mqttService.observe('my/topic').subscribe((message: IMqttMessage) => {
Line 21: this._mqttService.unsafePublish(topic, message, {qos: 1, retain: true});
PLEASE HELP, THANKS
</code></pre>

**Comment by sclausen** [comment]
I installed ionic@3.9.2 and just ran `ionic serve` after `npm install` in your project.
![everything-works-fine](https://user-images.githubusercontent.com/916076/45352772-90570780-b5b9-11e8-9ac1-043b7da6c65b.png)

Everything seems to work fine.

Your error regarding `'Subscription' is not assignable to type 'Subscription'` though is typical for conflicting rxjs versions. So it seems you aren't using a compatible version of rxjs with `ngx-mqtt`. The `package.json` in the repository you posted looks fine, and I can compile and run without any error, so are you really sure you have a clean project?

I can't guess, what you did with the code on the webpage. Your error states that what you did is inherently wrong, but without any code I can just guess. The example code on the webpage would be for a `ngx-mqtt` >= 6 though.

**Comment by nchanti** [comment]
Sebastian,

Thank you for looking into this. I will start over with a clean install of everything (like you did). Are you on a MAC OS?
If yes, could you please share the path of where each component is installed (ngx-mqtt, rxjs & ionic). I am wondering if my environment has components in the wrong path.

Thanks,
Nicholas

**Comment by sclausen** [comment]
Sorry, I'm not using mac. All dependencies are installed into the same directory though, regardless of the operating system. Everything npm installs locally goes into the `./node_modules` folder.
lets see what a clean install does for you :wink:

**Comment by nchanti** [comment]
Working! Once I did a clean install with everything in the same ./node_modules I got the App to run.

However, I am seeing the follow message when the App uses ngx-mqtt to connect:
1536703630: New connection from ::1 on port 1883.
1536703630: Socket error on client <unknown>, disconnecting.


  1.  I am using Mosquitto 3.1.1 running on my same machine (localhost)
  2.  I made the following changes to the “app.module.ts” file
     *   export const MQTT_SERVICE_OPTIONS : IMqttServiceOptions = {
     *     hostname: 'localhost',
     *     port: 1883,
     *     username : "",
     *     password : ""
     *   };
  3.  Have you seen this before?
  4.  I can’t tell if the root cause is Mosquitto or ngx-mqtt
  5.  However, I successfully ran a Python client to connect to the same Mosquitto and that works

Thanks for any insite or suggestions

**Comment by sclausen** [comment]
You clearly haven't read [the manual](https://sclausen.github.io/ngx-mqtt/) carefully enough, otherwise you wouldn't have made this very basic misconfiguration.

I'm really sorry, but this is an issue tracker of a spare time open source project, not a support chat. If you have any issues which are clearly not a bug or missing feature please ask a question on [stackoverflow.com](https://stackoverflow.com/).

**Comment by nchanti** [comment]
Sebastian, thank you for all you help.
-Nicholas
