### ISSUE TITLE
Secure Web Socket

### ISSUE THREAD

**Issue by roberttodor** [sclausen/ngx-mqtt#116]
I am using your example and it works. But I want to use Secure webSocket.
This is my broker mosquitto.config file:

listener 1884
protocol websockets
cafile   /etc/mosquitto/certificates/ca.crt
certfile /etc/mosquitto/certificates/broker.crt
keyfile  /etc/mosquitto/certificates/broker.key
require_certificate true

It is posible to import the certificates into my app.module.ts ? Or what i have to do to make it work?
Best regards!

**Comment by sclausen** [comment]
Please have a look at #20
