### ISSUE TITLE
debugger cause onClose after few second

### ISSUE THREAD

**Issue by dario-frongillo** [sclausen/ngx-mqtt#117]
- [X] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report 
- [ ] Feature request

## Current behavior
hi,
i have an angular webapp that use the latest version of ngx-mqtt. If i need to debug my webapp stopping the flow with some break point, after few second stopped i receive the event **onClose** of the lib.
is it normal ? is it a timeout ? how can manage it ? 

## Expected behavior
if i stop the flow of my software few second in debugger in browser console,mqtt should not close my connection. please tell me if there is an option to mangage it ( a timeout for i.e)

## What is the motivation / use case for changing the behavior?
it is very important debug the app without break each time the connection after few second

## Environment

<pre><code>
ngx-mqtt version: 6.6.0
</code></pre>

**Comment by sclausen** [comment]
Please follow the issue template.

**Comment by dario-frongillo** [comment]
sorry i have updated the message

**Comment by dario-frongillo** [comment]
maybe can be an issue related the keepalive ? can you kindle me suggest a config to correctly debug the web app without raise close event ? thnx

**Comment by sclausen** [comment]
Unfortunately a proper reproduction is still missing. For example I don‘t know at which point you set your debugger. Please provide a repository in which I can reproduce your issue.

**Comment by sclausen** [comment]
The standard value of `keepalive` is 60 seconds but I think this isn‘t really working here, since the`close` event is emitted way earlier when the debugger has stopped the script. Setting `keepalive` to an insane amount seems to work, but this solution doesn‘t seem to cure the illness, but a symptom. I‘ll have a look, in I can reproduce this behavior with plain `mqtt.js` and open an issue for this.

**Comment by sclausen** [comment]
It seems I have overwritten the standard mqtt.js keepalive of 60 seconds with 10 seconds. Because of this mistake your debugger causes the onClose event way earlier than expected.
Version [6.7.0](https://github.com/sclausen/ngx-mqtt/releases/tag/6.7.0) fixes this issue.

**Comment by dario-frongillo** [comment]
Thanks slausen.. so now ngx-mqtt works as mqtt.js about default mqtt keepalive value used ?

**Comment by sclausen** [comment]
Yes, the default keepalive of mqtt.js will be used if none is given.
