### ISSUE TITLE
Connection retrying mechanism

### ISSUE THREAD

**Issue by adibacco** [sclausen/ngx-mqtt#119]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request

## Current behavior

If the network goes down between my chrome browser (running the ngx-mqtt) and the MQTT broker sometimes the ngx-mqtt component stops retrying to restore the connection.

## Expected behavior

The right behaviour should be retrying to connect forever.

## Environment

<pre><code>
ngx-mqtt version: 6.4.1

- Broker 
Mosquitto

Others:

Chrome Version 70.0.3538.67 (Official Build) (64-bit)
</code></pre>

![image](https://user-images.githubusercontent.com/2692833/47075698-55ba3d80-d1fd-11e8-9834-a3a3bf2a2079.png)

**Comment by sclausen** [comment]
Would you be so kind and follow the issue template?

**Comment by adibacco** [comment]
What was wrong? I followed the template.

**Comment by sclausen** [comment]
>Minimal reproduction of the problem with instructions
