### ISSUE TITLE
Vendor is missing

### ISSUE THREAD

**Issue by markdegrootnl** [sclausen/ngx-mqtt#123]
- [X] **I have searched for similar issues in this repository, but couldn't find one.**
- [X] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report  
- [ ] Feature request

## Current behavior

Building errors with `Cannot find module '../vendor/mqtt.min.js'.`

## Expected behavior

Building works

## Environment

<pre><code>
ngx-mqtt version: master

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
I'm so sorry. Here is [6.8.1](https://github.com/sclausen/ngx-mqtt/releases/tag/6.8.1)
