### ISSUE TITLE
Publish() requires subscription to complete - document or fix?

### ISSUE THREAD

**Issue by sirockin** [sclausen/ngx-mqtt#125]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior

MqttService.publish() will not actually publish the value unless subscribe is invoked.

## Expected behavior

Should publish whether subscribe is invoked or not. (Or documentation should be updated to reflect this).

## Minimal reproduction of the problem with instructions

Invoke MqttService.publish() without a subscription - eg remove `.noop()` from #publish test as follows:

```TypeScript
  it('#publish without subscribe', (done) => {
    mqttService.publish('mqtt-rx/tests/ws/publishNoSubscribe/' + currentUuid, 'publish');
    setTimeout(function(){
      done();
    }, 2000);
  });
```

## What is the motivation / use case for changing the behavior?

It is not clear from the documentation nor the name of the method that a subscription is required to make it work.

Although I recognise that best practices are to check success/failure and hence to subscribe, there are always cases where 'fire and forget' is appropriate.

So ideally I would want to do one of the following:
1. Fix so it works whether subscribed or not
1. Rename to something like `publishOnObserve()`
1. Update documentation to state clearly that a subscription to the returned observable is necessary 

## Environment

<pre><code>
ngx-mqtt version: 6.8.2
Broker: any
</code></pre>

**Comment by sclausen** [comment]
I think the documentation is absolutely clear about the behavior of `publish`. The documentation says:
```
This method publishes a message for a topic with optional options.
The returned observable will emit empty value and complete, if publishing was successful
and will throw an error, if the publication fails.
```
So it should be clear that this is a cold observable. It might be a hurtful presumption, but did you understand [how observables work](https://medium.com/@luukgruijs/understanding-hot-vs-cold-observables-62d04cf92e03)?

**Comment by sirockin** [comment]
Hi Sebastian! Thanks for replying so quickly 

I'm not hurt but yes I do understand very well how observables work :-). 

Nonetheless, for what it's worth I think the documentation could be clearer. I don't think it is clear that it's a cold observable and even it was, casual users who are used to paradigms like `async` - `await` may  not realise that a subscription is required for it to execute. I don't think it would do any harm to add the following words to the end of the documentation:

> The method requires a subscription to the returned observable, otherwise it will not execute.

Sorry if this sounds like a criticism - you have an excellent library and I'm just trying to provide useful feedback. Anyway it's your call.

**Comment by sclausen** [comment]
Do you like the different wording?

**Comment by sirockin** [comment]
Hi Sebastian. Yes, thanks for updating. 

BTW did you see my further response to #120 regarding forking to a back end version? It's all transferred over quite smoothly.
