### ISSUE TITLE
Angular 7 ngx-mqtt

### ISSUE THREAD

**Issue by sghazagh** [sclausen/ngx-mqtt#126]
NPM installs the 5.5.0. if I use ngx-mqtt@next it installs 6.0.0-alpha.

How can I install ngx-mqtt 6.8.3?
I use this command but does not work:

`npm i ngx-mqtt@6.8.3 --save`

Can you please advise what version works with angula 7.2.2?
Using: Node 10.15.0 & NPM 6.4.1

ng version
-----------------------------------------------------------
Angular CLI: 7.2.3
Node: 10.15.0
OS: win32 x64
Angular: 7.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.3
@angular-devkit/build-angular     0.12.3
@angular-devkit/build-optimizer   0.12.3
@angular-devkit/build-webpack     0.12.3
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.2.3
@angular/cli                      7.2.3
@angular/fire                     5.1.1
@angular/http                     5.2.11
@ngtools/webpack                  7.2.3
@schematics/angular               7.2.3
@schematics/update                0.12.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

**Comment by sclausen** [comment]
If you just execute `npm i ngx-mqtt`, it doesn't installs`6.8.3`? Could you please provide an example repository containig the result of your installation steps?
`6.8.3` should work with angular 7 though.

**Comment by sclausen** [comment]
I can't reproduce your issue, everything installs just fine in the correct versions.
Would you be so kind and provide an example repository of the results of what you described to me?

**Comment by sghazagh** [comment]
Definitly, but sorry I don't understand what "example repository" means.
I have a project on my local and I am using subversion in my lan to keep the revisions.

The only thing I havn't mentioned is that, I have upgraded my Angular 2 project so the package .json was there.

I removed the ngx-mqtt line from json file and removed the folder from my node-modules to be sure there files are not there.

so when I tried above explained command it just installs version 5.5.0.

Tell me what you need to be able to track it down, then I send you what you need.

and here is output of what I get if I run it...
`$ npm i ngx-mqtt --save
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > pre-commit@1.2.2 install C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\pre-commit
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > spawn-sync@1.0.15 postinstall C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\spawn-sync
npm ERR! prepareGitDep > node postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > ngrok@2.1.8 postinstall C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\ngrok
npm ERR! prepareGitDep > node ./postinstall.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep ngrok - downloading binary https://bin.equinox.io/a/chRZWPptE7w/ngrok-2.1.1-windows-amd64.zip ...
npm ERR! prepareGitDep ngrok - binary downloaded...
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! prepareGitDep npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! prepareGitDep npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep ngrok - error unpacking binary Error: You cannot extract a file outside of the target path
npm ERR! prepareGitDep     at C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\lib\decompress-zip.js:95:21
npm ERR! prepareGitDep     at Array.map (<anonymous>)
npm ERR! prepareGitDep     at C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\lib\decompress-zip.js:91:25
npm ERR! prepareGitDep     at _fulfilled (C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\node_modules\q\q.js:854:54)
npm ERR! prepareGitDep     at C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\node_modules\q\q.js:883:30
npm ERR! prepareGitDep     at Promise.promise.promiseDispatch (C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\node_modules\q\q.js:816:13)
npm ERR! prepareGitDep     at C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\node_modules\q\q.js:624:44
npm ERR! prepareGitDep     at runSingle (C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\node_modules\q\q.js:137:13)
npm ERR! prepareGitDep     at flush (C:\Users\Saeid\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-a0e513f6\node_modules\decompress-zip\node_modules\q\q.js:125:13)
npm ERR! prepareGitDep     at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! prepareGitDep npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! ngrok@2.1.8 postinstall: `node ./postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the ngrok@2.1.8 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\Saeid\AppData\Roaming\npm-cache\_logs\2019-01-27T22_03_44_420Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Saeid\AppData\Roaming\npm-cache\_logs\2019-01-27T22_03_45_409Z-debug.log
`

**Comment by gmarab** [comment]
I have the same problem too.
I attach the log file.
[2019-01-27T22_35_38_731Z-debug.log](https://github.com/sclausen/ngx-mqtt/files/2800605/2019-01-27T22_35_38_731Z-debug.log)

**Comment by sghazagh** [comment]
I did it for brand new Angualr 7 project and got a same issue....
Only Angular-cli installed, so I cannot install the ngx-mqtt at all!!!

[Image HERE](https://drive.google.com/file/d/1-5fauc7nt8sCpaivAYvIRs2FyVVnjWb7)

**Comment by padiyan** [comment]
Hi, I'm also facing the same issue. Please find below npm log,

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'ngx-mqtt' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session 7fc8840f8db5a0c1
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/ngx-mqtt 193ms (from cache)
8 silly pacote tag manifest for ngx-mqtt@latest fetched in 285ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule ngx-mqtt@6.8.3 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/ssri 162ms (from cache)
15 silly pacote range manifest for ssri@>=6.0.0 fetched in 169ms
16 silly resolveWithNewModule ssri@6.0.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/ecstatic 208ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 217ms (from cache)
19 silly pacote range manifest for ecstatic@>=3.2.0 fetched in 253ms
20 silly resolveWithNewModule ecstatic@3.3.0 checking installable status
21 silly pacote version manifest for @types/node@10.3.2 fetched in 257ms
22 silly resolveWithNewModule @types/node@10.3.2 checking installable status
23 verbose prepareGitDep undefined: installing devDeps and running prepare script.
24 error prepareGitDep 1>
24 error prepareGitDep > pre-commit@1.2.2 install C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\pre-commit
24 error prepareGitDep > node install.js
24 error prepareGitDep
24 error prepareGitDep
24 error prepareGitDep > spawn-sync@1.0.15 postinstall C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\spawn-sync
24 error prepareGitDep > node postinstall
24 error prepareGitDep
24 error prepareGitDep
24 error prepareGitDep > ngrok@2.1.8 postinstall C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\ngrok
24 error prepareGitDep > node ./postinstall.js
24 error prepareGitDep
24 error prepareGitDep ngrok - downloading binary https://bin.equinox.io/a/chRZWPptE7w/ngrok-2.1.1-windows-amd64.zip ...
24 error prepareGitDep ngrok - binary downloaded...
25 error prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
25 error prepareGitDep npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
25 error prepareGitDep npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
25 error prepareGitDep npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
25 error prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
25 error prepareGitDep npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
25 error prepareGitDep npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
25 error prepareGitDep npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
25 error prepareGitDep npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
25 error prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
25 error prepareGitDep npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
25 error prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
25 error prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
25 error prepareGitDep npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
25 error prepareGitDep npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
25 error prepareGitDep npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
25 error prepareGitDep ngrok - error unpacking binary Error: You cannot extract a file outside of the target path
25 error prepareGitDep     at C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\lib\decompress-zip.js:95:21
25 error prepareGitDep     at Array.map (<anonymous>)
25 error prepareGitDep     at C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\lib\decompress-zip.js:91:25
25 error prepareGitDep     at _fulfilled (C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\node_modules\q\q.js:854:54)
25 error prepareGitDep     at self.promiseDispatch.done (C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\node_modules\q\q.js:883:30)
25 error prepareGitDep     at Promise.promise.promiseDispatch (C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\node_modules\q\q.js:816:13)
25 error prepareGitDep     at C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\node_modules\q\q.js:624:44
25 error prepareGitDep     at runSingle (C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\node_modules\q\q.js:137:13)
25 error prepareGitDep     at flush (C:\Users\Pandithurai\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-34753ab8\node_modules\decompress-zip\node_modules\q\q.js:125:13)
25 error prepareGitDep     at _combinedTickCallback (internal/process/next_tick.js:131:7)
25 error prepareGitDep     at process._tickCallback (internal/process/next_tick.js:180:9)
25 error prepareGitDep npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
25 error prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
25 error prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
25 error prepareGitDep
25 error prepareGitDep npm ERR! code ELIFECYCLE
25 error prepareGitDep npm ERR! errno 1
25 error prepareGitDep npm ERR! ngrok@2.1.8 postinstall: `node ./postinstall.js`
25 error prepareGitDep npm ERR! Exit status 1
25 error prepareGitDep npm ERR!
25 error prepareGitDep npm ERR! Failed at the ngrok@2.1.8 postinstall script.
25 error prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
25 error prepareGitDep
25 error prepareGitDep npm ERR! A complete log of this run can be found in:
25 error prepareGitDep npm ERR!     C:\Users\Pandithurai\AppData\Roaming\npm-cache\_logs\2019-01-28T01_58_02_316Z-debug.log
26 silly fetchPackageMetaData error for mqtt@github:mqttjs/MQTT.js#16848192d5e31918d5b63a697803231caef74a3a Non-registry package missing package.json: mqtt@github:mqttjs/MQTT.js#16848192d5e31918d5b63a697803231caef74a3a.
27 silly saveTree delete@1.0.0
27 silly saveTree `-- ngx-mqtt@6.8.3
27 silly saveTree   +-- @types/node@10.3.2
27 silly saveTree   +-- ecstatic@3.3.0
27 silly saveTree   `-- ssri@6.0.1
28 verbose stack Error: Non-registry package missing package.json: mqtt@github:mqttjs/MQTT.js#16848192d5e31918d5b63a697803231caef74a3a.
28 verbose stack     at BB.join (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\finalize-manifest.js:160:23)
28 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
28 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:14:44)
28 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:29:30)
28 verbose stack     at Promise.eval (eval at thenCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:14:16), <anonymous>:6:20)
28 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:566:21)
28 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
28 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
28 verbose stack     at Promise._fulfill (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
28 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\nodeback.js:42:21)
28 verbose stack     at emitNone (events.js:111:20)
28 verbose stack     at Object.emit (events.js:208:7)
28 verbose stack     at Object.Parser.on._ (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:75:14)
28 verbose stack     at emitTwo (events.js:126:13)
28 verbose stack     at Object.emit (events.js:214:7)
28 verbose stack     at Object.[emit] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:229:12)
29 verbose cwd C:\Users\Pandithurai\Desktop\work\delete
30 verbose Windows_NT 10.0.17134
31 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "ngx-mqtt"
32 verbose node v8.11.3
33 verbose npm  v5.6.0
34 error code ENOPACKAGEJSON
35 error package.json Non-registry package missing package.json: mqtt@github:mqttjs/MQTT.js#16848192d5e31918d5b63a697803231caef74a3a.
36 error package.json npm can't find a package.json file in your current directory.
37 verbose exit [ 1, true ]

**Comment by sclausen** [comment]
@sghazagh with example repository I mean a github repository containing the code of a bare angular-cli project where you installed ngx-mqtt with `npm i ngx-mqtt` and it installs an old version of it.

Each one of you seem to have some slightly different error logs, but you all have in common, that you can't install a dependency called `ngrok`, which seems to be installed on windows only.
```
Error: ngrok@2.1.8 postinstall: `node ./postinstall.js`
```
Back in early 2016, [this issue has been reported](https://github.com/bubenshchykov/ngrok/issues/44), but it should've been resolved in an earlier version of `ngrok`. now used by another transitive dependency of this library.

@padiyan Beats me, why you get the `ENOPACKAGEJSON` additionally to the `ngrok` error.

I don't want to start a debate on web development on windows and I'm really sorry that you get this error, but I don't have time to investigate any issues which are windows only.

**Comment by sclausen** [comment]
> However, if you wanted to come up with 'sorry you cannot work on this issue because of windows' so why you have started it in first place my friend?!!!

What do you mean with `started it`? A discussion about operating systems? I didn't. I simply wanted to tell you that `I don't have time to investigate any issues which are windows only` **without starting any debate** and preventing exactly what happens now.
>We all are working in different environment.

Totally acceptable but not the point.
> I have been working in Linux platforms in last 2 decades so I personally quite familiar with Linux and even I am developing Linux OS for ARM devices.

I didn't assumed anything about your experience. Neither does that contribute to this issue. I don't know why you think you have to clarify your background…

> However, the corporate environment and enterprise setup sometime dictate what environment the developers have to work on. So it's not something that individual can decide.

I'm totally aware of that.
> So consider situation that we need and have to work in Windows environment.

I absolutely considered that situation too.
> but if we cannot get it working, perhaps we all come to the point that we have to get away from it...

Thanks for pointing out the obvious.

I really don't know the reason behind the accusatory tone of your texts or where your exaggerated expectations come from, but my mom taught me to be nice to persons who give away stuff for free, even if you decline thankfully for any reason (you don't like it, you're allergic to peanuts or whatever).

## TL;DR

Since this is an unpaid spare time project not backed up by any corporation I take the liberties as the developer of this project to simply refuse investigating bugs where I'm forced to use Windows. I don't mind if you're using it but I simply don't wan't to. That's called tolerance.

I'll keep this issue open, in case someone comes up with a solution or any comments.

**Comment by sclausen** [comment]
> Meanwhile, ngrok itself can be installed without any issue!

You installed the latest version of ngrok (3.1.0). The transitive dependency is `ngrok@2.1.8`

**Comment by sghazagh** [comment]
ngrok 2.1.8 itself returns the same error.
can you update the dependency to use 3.1.0 instead and we check?

shouldn't affect ngx-mqtt though, does it?

**Comment by adenysen** [comment]
So - I am new to the project (and am also hoping to use this library on a windows machine).  To see if I could build the project I tried cloning the ngx-mqtt repo from github to my local machine and then ran `npm install` on a windows 10 machine and ran into a similar error.  See attached file for full npm log.

[npm install windows.log](https://github.com/sclausen/ngx-mqtt/files/2809173/npm.install.windows.log)

**Comment by sclausen** [comment]
Okay, just adding `ngrok@3.1.0` doesn't work. It still want's to install `ngrok@2.1.8`, which downloads in your case `ngrok-2.1.1-windows-amd64.zip` and then the unpacking fails with 
```
ngrok - error unpacking binary Error: You cannot extract a file outside of the target path
```
I have absolutely no idea what to do. I know, I can override npm dependency versions with npm-shrinkwrap, but I have no idea how to start finding out which packages I have to override.
Has anyone else any ideas?

**Comment by adenysen** [comment]
[npm-remote-ls](https://www.npmjs.com/package/npm-remote-ls) appears to decipher the dependency graph.  I ran this against version 6.8.3 (before the explicit dependency to ngrok was added) using the command `npm-remote-ls ngx-mqtt@6.8.3` and surprisingly it didn't spit out the dependency on ngrok.  See attached output.  sclausen, I really appreciate you responding to this issue - especially since it seems to be a Windows only problem.  I will continue to poke around myself to see if I can figure out where this dependency is coming from.

[npm-remote-ls ngx-mqtt.txt](https://github.com/sclausen/ngx-mqtt/files/2809909/npm-remote-ls.ngx-mqtt.txt)

**Comment by adenysen** [comment]
So I tried running `npm install .` within the `\node_modules\mqtt` directory and obtained the same issue.

Given that, the issue seems to be related to the `MQTT.js` library itself.  In looking a bit futher I can see the `devDependencies` section contains a reference to `zuul-ngrok@4.0.0` within [package.json](https://github.com/mqttjs/MQTT.js/blob/master/package.json) - and `zuul-ngrok@4.0.0` has a dependency on [ngrok@2.1.8](https://github.com/rase-/zuul-ngrok/blob/03742b3d34c15c441018bbeefa1e705dc55711dd/package.json).

Though `zuul-ngrok` has been updated to 4.1.0 (in github) (with hthe updated reference to ngrok@3.1.0), mqtt.js references 4.0.0 and npjms.com still only has [zuul-ngrok](https://www.npmjs.com/package/zuul-ngrok).

The fix appears to have the `zuul-ngrok` author updated npjms.com with version 4.1.0 of his library - so mqtt.js can then updated to that version of the library.

**Comment by sghazagh** [comment]
Seems hat it is the rights trace!

Perhaps someone like @sciausen can aske them to do so by explaining the issue....

**Comment by sclausen** [comment]
I don't want to bother the maintainer of MQTT.js with something currently unresolvable until  @rase- publishes  the new version.

**Comment by BastienvP3** [comment]
I had the same problem using Windows. Then I tried using Yarn instead of NPM and it magically worked. I'm investigating why did it work on Yarn and not on NPM...

**Comment by sghazagh** [comment]
Thanks for your comment.
I also have used yarn as dependencies have installed.
I got my application working just fine with MQTT functionality.

The only issue I experience now is that, when I build my app in production (--prod), I get an error regarding promises which I don't know this is 'ngx-mqtt' problem or there is something wrong in Angular itself.
I only get that error in production which does not let application loads, have no issue in development environment and app works just fine!!!
![error](https://user-images.githubusercontent.com/12246858/53544622-d1989f00-3b7a-11e9-9e15-a20bb54fe73e.png)

Anyone can advise?

**Comment by sclausen** [comment]
It seems like you're using the wrong scheme to connect to websocket. You should replace `http://127.0.0.1:5500` with `ws://127.0.0.1:5500`

**Comment by sghazagh** [comment]
No, that's my local live server. The web socket is set inside my app pointing to a server in my LAN.
However, when it's not in production build, it's just fine!!!

**Comment by sclausen** [comment]
Would you be so kind an post a repository with the reproduction of this issue?

**Comment by sghazagh** [comment]
Unfortunately due to the custom setup of home automation system that I have, producing this issue out of my LAN is not possible.
I have more than 25 custom sensor in a MQTT mesh network at my home which are listed in centralaized controller server and without them, the app is useless :(

**Comment by sclausen** [comment]
I didn' mean I want to see your whole app, I want to know if you could strip down your code to the bare minimum where you use ngx-mqtt and see if it still fails. I would like to see a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).

**Comment by sghazagh** [comment]
Hi,
I just created new Angular  app from scratch.
Used Yarn to install ngx-mqtt and only installed rxjs and rxjs-compat.
The rest are out of the box Angular project.

My bar-bone mqtt test app is working just fine in both development and production environment.

Perhaps there is an issue with my main app using the HttpClient to fetch data in my page.
Not sure but I belive the issue is not with ngx-mqtt.

The only questions left are:

- why ngx-mqtt works fine with yarn but not npm
why ngx-mqtt need 'handlebar' as dependency?
`warning " > ngx-mqtt@6.8.4" has unmet peer dependency "handlebars@^4.0.11".`

**Comment by sclausen** [comment]
I don't know anymore, why I added handlebars. Whatever the reason was, it still builds without it, so I removed it with [6.8.5](https://github.com/sclausen/ngx-mqtt/releases/tag/6.8.5).

**Comment by sclausen** [comment]
Great to hear that it works with yarn.
