### ISSUE TITLE
npm i --save ngx-mqtt not happening v_6.8.5

### ISSUE THREAD

**Issue by chaitanyaVadlamudi** [sclausen/ngx-mqtt#127]
A day ago you updated the ngx-mqtt library to 6.8.5  and when tried to install it, it's not installing and throwing the err as follows:

npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > pre-commit@1.2.2 install C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\pre-commit
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > spawn-sync@1.0.15 postinstall C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\spawn-sync
npm ERR! prepareGitDep > node postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > ngrok@2.1.8 postinstall C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\ngrok
npm ERR! prepareGitDep > node ./postinstall.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep ngrok - downloading binary https://bin.equinox.io/a/chRZWPptE7w/ngrok-2.1.1-windows-amd64.zip ...
npm ERR! prepareGitDep ngrok - binary downloaded...
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm ERR! prepareGitDep npm WARN deprecated   npm i nyc
npm ERR! prepareGitDep npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! prepareGitDep npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! prepareGitDep npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated istanbul@0.2.16: This module is no longer maintained, try this instead:
npm ERR! prepareGitDep npm WARN deprecated   npm i nyc
npm ERR! prepareGitDep npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! prepareGitDep npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! prepareGitDep npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep ngrok - error unpacking binary Error: You cannot extract a file outside of the target path
npm ERR! prepareGitDep     at C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\lib\decompress-zip.js:95:21
npm ERR! prepareGitDep     at Array.map (<anonymous>)
npm ERR! prepareGitDep     at C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\lib\decompress-zip.js:91:25
npm ERR! prepareGitDep     at _fulfilled (C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\node_modules\q\q.js:854:54)
npm ERR! prepareGitDep     at C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\node_modules\q\q.js:883:30
npm ERR! prepareGitDep     at Promise.promise.promiseDispatch (C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\node_modules\q\q.js:816:13)
npm ERR! prepareGitDep     at C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\node_modules\q\q.js:624:44
npm ERR! prepareGitDep     at runSingle (C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\node_modules\q\q.js:137:13)
npm ERR! prepareGitDep     at flush (C:\Users\hp\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-6ef75273\node_modules\decompress-zip\node_modules\q\q.js:125:13)
npm ERR! prepareGitDep     at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! ngrok@2.1.8 postinstall: `node ./postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the ngrok@2.1.8 postinstall script.

Thank you

**Comment by sclausen** [comment]
Would you please try to install with yarn? It seems that installing on windows is in general broken, but removing ngrok as an explicit dependency (otherwise it only seems to be installed on windows) may have broken it too.
Would you be so kind and try installing with yarn?

**Comment by mfhs** [comment]
I am trying to install this on a Angular 6+ test project but could not able to with the command-

npm i ngx-mqtt

is there any possibility to install using the above (not using yarn)? It will be really helpful if I can install as mentioned here https://www.npmjs.com/package/ngx-mqtt

Thanks in advance.

**Comment by sclausen** [comment]
@mfhs what‘s your operating system?

**Comment by mfhs** [comment]
> @mfhs what‘s your operating system?

Windows 7 64-bit

**Comment by sclausen** [comment]
Installing ngx-mqtt on Windows doesn‘t seem to work without me explicitly adding ngrok in a special Version to ngx-mqtt, which would force non Windows users to unnecessarily have it as a dependency too.
If you‘re willing to participate in a little experiment, I would be really grateful. Could you please execute `npm i ngrok@3.1.0` before installing ngx mqtt?

**Comment by mfhs** [comment]
> Installing ngx-mqtt on Windows doesn‘t seem to work without me explicitly adding ngrok in a special version to ngx-mqtt, which would force non Windows users to unnecessarily have it as a dependency too.
> If you‘re willing to participate in a little experiment, I would be really grateful. Could you please execute `npm i ngrok@3.1.0` before installing ngx mqtt?

Sure, I will try and let you know.

**Comment by mfhs** [comment]
Hi, find the log after execution of the command => npm i ngrok@3.1.0

> ngrok@3.1.0 postinstall K:\Projects\node_modules\ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip
ngrok - downloading progress: 14819314/14819314
ngrok - binary downloaded to C:\Users\xxxx\.ngrok\aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS13aW5kb3dzLWFtZDY0LnppcA==.zip
ngrok - unpacking binary
ngrok - binary unpacked to K:\Projects\node_modules\ngrok\bin\ngrok.exe
npm WARN @angular/cdk@7.3.1 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@7.3.1 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@7.3.1 requires a peer of @angular/animations@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@7.3.1 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@7.3.1 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ngrok@3.1.0
added 16 packages from 32 contributors and audited 39066 packages in 126.557s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by sclausen** [comment]
And installing ngx-mqtt aftewards worked or failed?

**Comment by mfhs** [comment]
> And installing ngx-mqtt aftewards worked or failed?

The execution some time...

npm i ngx-mqtt
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > pre-commit@1.2.2 install C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\pre-commit
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > spawn-sync@1.0.15 postinstall C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\spawn-sync
npm ERR! prepareGitDep > node postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > ngrok@2.1.8 postinstall C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\ngrok
npm ERR! prepareGitDep > node ./postinstall.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep ngrok - downloading binary https://bin.equinox.io/a/chRZWPptE7w/ngrok-2.1.1-windows-amd64.zip ...
npm ERR! prepareGitDep ngrok - binary downloaded...
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm ERR! prepareGitDep npm WARN deprecated   npm i nyc
npm ERR! prepareGitDep npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! prepareGitDep npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm ERR! prepareGitDep npm WARN deprecated istanbul@0.2.16: This module is no longer maintained, try this instead:
npm ERR! prepareGitDep npm WARN deprecated   npm i nyc
npm ERR! prepareGitDep npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! prepareGitDep npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! prepareGitDep npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use
 tar module instead: https://npmjs.com/tar
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep ngrok - error unpacking binary Error: You cannot extract a file outside of the target path
npm ERR! prepareGitDep     at C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\lib\decompress-zip.js:95:21
npm ERR! prepareGitDep     at Array.map (<anonymous>)
npm ERR! prepareGitDep     at C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\lib\decompress-zip.js:91:25
npm ERR! prepareGitDep     at _fulfilled (C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\node_modules\q\q.js:854:54)
npm ERR! prepareGitDep     at C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\node_modules\q\q.js:883:30
npm ERR! prepareGitDep     at Promise.promise.promiseDispatch (C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\node_modules\q\q.js:816:13)
npm ERR! prepareGitDep     at C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\node_modules\q\q.js:624:44
npm ERR! prepareGitDep     at runSingle (C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\node_modules\q\q.js:137:13)
npm ERR! prepareGitDep     at flush (C:\Users\*****\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-80770c08\node_modules\decompress-zip\node_modules\q\q.js:125:13)
npm ERR! prepareGitDep     at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! ngrok@2.1.8 postinstall: `node ./postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the ngrok@2.1.8 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\*****\AppData\Roaming\npm-cache\_logs\2019-03-08T18_55_19_736Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Roaming\npm-cache\_logs\2019-03-08T18_55_21_358Z-debug.log

**Comment by gischy** [comment]
gleiches problem auf windows 10:
$ npm install ngx-mqtt --save
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > pre-commit@1.2.2 install C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\pre-commit
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > spawn-sync@1.0.15 postinstall C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\spawn-sync
npm ERR! prepareGitDep > node postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > ngrok@2.1.8 postinstall C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\ngrok
npm ERR! prepareGitDep > node ./postinstall.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep ngrok - downloading binary https://bin.equinox.io/a/chRZWPptE7w/ngrok-2.1.1-windows-amd64.zip ...
npm ERR! prepareGitDep ngrok - binary downloaded...
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated istanbul@0.2.16: This module is no longer maintained, try this instead:
npm ERR! prepareGitDep npm WARN deprecated   npm i nyc
npm ERR! prepareGitDep npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm ERR! prepareGitDep npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! prepareGitDep npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! prepareGitDep npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm ERR! prepareGitDep npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep ngrok - error unpacking binary Error: You cannot extract a file outside of the target path
npm ERR! prepareGitDep     at C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\lib\decompress-zip.js:95:21
npm ERR! prepareGitDep     at Array.map (<anonymous>)
npm ERR! prepareGitDep     at C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\lib\decompress-zip.js:91:25
npm ERR! prepareGitDep     at _fulfilled (C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\node_modules\q\q.js:854:54)
npm ERR! prepareGitDep     at C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\node_modules\q\q.js:883:30
npm ERR! prepareGitDep     at Promise.promise.promiseDispatch (C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\node_modules\q\q.js:816:13)
npm ERR! prepareGitDep     at C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\node_modules\q\q.js:624:44
npm ERR! prepareGitDep     at runSingle (C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\node_modules\q\q.js:137:13)
npm ERR! prepareGitDep     at flush (C:\Users\nona\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-289aa8a7\node_modules\decompress-zip\node_modules\q\q.js:125:13)
npm ERR! prepareGitDep     at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! ngrok@2.1.8 postinstall: `node ./postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the ngrok@2.1.8 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\nona\AppData\Roaming\npm-cache\_logs\2019-03-12T21_55_20_646Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nona\AppData\Roaming\npm-cache\_logs\2019-03-12T21_55_20_965Z-debug.log

**Comment by gischy** [comment]
#126

**Comment by chaitanyaVadlamudi** [comment]
Sorry for late comment. I tried with version 6.6.0 which  I used in other project on the same day  using npm i --save ngx-mqtt@6.6.0. And everything worked as expected.

**Comment by sclausen** [comment]
Yes, this error has eben introduced in the lägest version. It Inlay seems to affect windows with npm. Every other platform and Windows with yarn seems to work.
I don‘t know when I get the time to set up a development environment on a Windows machine to investigate this issue.

**Comment by sclausen** [comment]
So I managed to get some time to give it a try under Windows and I can't find out why `ngrok` is a dependency. `npm ls` or differnt tools didn't show any trace of ngrok in the dependency tree and installing it with yarn works like a charm and ngrok won't be installed. Sorry, for all Windows users out there, but I can't get it to work without yarn on Windows.

**Comment by letsmakesense** [comment]
Upgrade to 6.8.5 doesn't work on Ubuntu 18.04. neither. But got a different error:

npm ERR! prepareGitDep Parse error at 0:9015,65
npm ERR! prepareGitDep             result += currentValue.reduce((currentLength, value) => {
npm ERR! prepareGitDep                                                                  ^
npm ERR! prepareGitDep ERROR: Invalid assignment
npm ERR! prepareGitDep     at JS_Parse_Error.get (eval at <anonymous> (/tmp/empty-cache/_cacache/tmp/git-clone-9c1e34df/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
npm ERR! prepareGitDep     at fatal (/tmp/empty-cache/_cacache/tmp/git-clone-9c1e34df/node_modules/uglify-js/bin/uglifyjs:296:53)
npm ERR! prepareGitDep     at run (/tmp/empty-cache/_cacache/tmp/git-clone-9c1e34df/node_modules/uglify-js/bin/uglifyjs:240:9)
npm ERR! prepareGitDep     at ReadStream.<anonymous> (/tmp/empty-cache/_cacache/tmp/git-clone-9c1e34df/node_modules/uglify-js/bin/uglifyjs:173:9)
npm ERR! prepareGitDep     at ReadStream.emit (events.js:194:15)
npm ERR! prepareGitDep     at endReadableNT (_stream_readable.js:1125:12)
npm ERR! prepareGitDep     at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! mqtt@2.18.8 browser-build: `rimraf dist/ && mkdirp dist/ && browserify mqtt.js -s mqtt > dist/mqtt.js && uglifyjs < dist/mqtt.js > dist/mqtt.min.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the mqtt@2.18.8 browser-build script.

Maybe due the new mqtt version in 6.8.5.

**Comment by sclausen** [comment]
@letsmakesense  Did yo do a normal `npm i ngx-mqtt`? Or did you tried to build it yourself?
mqtt.js should have been compiled into the library, so I'm a bit baffled about your error excerpt.
Neither I nor travis ci had problems building it, though. 

Would you be so kind and maybe open another issue for that and post a minimal (non)working example in it?

**Comment by letsmakesense** [comment]
Hi,

I forgot to tell that we don't use the regular npm registry, but  
artifactory for package management. Nevertheless a simple 'npm install  
ngx-mqtt' in a new folder works without problems. And strangely the 'npm  
install' in our project didn't throw the error today. So I won't open a  
ticket since it seems to be a local problem. Sorry for bothering you.



  Am 20.03.2019, 18:13 Uhr, schrieb Sebastian Clausen  
<notifications@github.com>:

> @letsmakesense  Did yo do a normal `npm i ngx-mqtt`? Or did you tried to  
> build it yourself?
> mqtt.js should have been compiled into the library, so I'm a bit baffled  
> about your error excerpt.
> Neither I nor travis ci had problems building it, though.
>
> Would you be so kind and maybe open another issue for that and post a  
> minimal (non)working example in it?
>


-- 
Peter Klein

Let's make sense GmbH
Webprojekte mit Sinn und Verstand

Tel.: 07071-1389980
E-Mail: p.klein@letsmakesense.de
Web: https://www.letsmakesense.de


Let's make sense GmbH
Magazinplatz 2, D-72072 Tübingen
Handelsregister: Amtsgericht Stuttgart, HRB 740355
Geschäftsführer: Peter Klein

**Comment by ievgennaida** [comment]
**npm
Angular 8.
ngx-mqtt": "~6.9.0"
Windows 10**
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! ngrok@2.1.8 postinstall: `node ./postinstall.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the ngrok@2.1.8 postinstall script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:

**Comment by sclausen** [comment]
> **npm Angular 8. ngx-mqtt": "~6.9.0" Windows 10**

It doesn't work to install `ngx-mqtt` on Windows with npm. Currently the only option is to use `yarn` instead of `npm`.

**Comment by sclausen** [comment]
@ievgennaida 
> **npm Angular 8. ngx-mqtt": "~6.9.0" Windows 10**

It doesn't work to install `ngx-mqtt` on Windows with npm. Currently the only option is to use `yarn` instead of `npm`.
