### ISSUE TITLE
I found that there are characters “.” in the subscription. Topic can't receive messages normally.

### ISSUE THREAD

**Issue by running-g** [sclausen/ngx-mqtt#129]
I use the ngx-mqtt link rabbit-mqtt today
If topic not included characters “.” ====== normal
if opic included characters “.” ,Unable to receive data

Tested====
if Subscribed topic ,then characters “.” will be "/"
so can not receive data

**Comment by sclausen** [comment]
Please fill out the issue template.

**Comment by sclausen** [comment]
![Visible confusion](https://media.giphy.com/media/1oJLpejP9jEvWQlZj4/giphy.gif)
