### ISSUE TITLE
trying it on ionic2

### ISSUE THREAD

**Issue by imphat** [sclausen/ngx-mqtt#13]
Hello, thanks for all the effort put into creating this library. I am trying to get it to work on a ionic2 project and got the following errors: 

##  installing: 
`npm WARN @angular/core@4.0.0-rc.5 requires a peer of zone.js@^0.8.4 but none was installed.`

## compiling: 
`[09:16:32]  typescript: ...gx-mqtt/node_modules/@angular/core/src/animation/animation_metadata_wrapped.d.ts, line: 12 
            Initializers are not allowed in ambient contexts.`

`      L13:   * @deprecated This symbol has moved. Please Import from @angular/animations instead!`

`[09:16:32]  typescript: node_modules/ngx-mqtt/node_modules/@angular/core/src/animation/dsl.d.ts, line: 34 
            Initializers are not allowed in ambient contexts. `

`      L35:   * @experimental Animation support is experimental.
[09:16:32]  typescript: node_modules/ngx-mqtt/node_modules/@angular/core/src/errors.d.ts, line: 9 `

`            Initializers are not allowed in ambient contexts. `

`       L8:  export declare function getDebugContext(error: Error): DebugContext;`
`[09:16:32]  typescript: node_modules/ngx-mqtt/node_modules/@angular/core/src/errors.d.ts, line: 10 `
`       L9:  export declare function getOriginalError(error: Error): Error;`
`      L10:  export declare function getErrorLogger(error: Error): (console: Console, ...values: any[]) => void;`

`            Initializers are not allowed in ambient contexts. `
`[09:16:32]  typescript: node_modules/ngx-mqtt/node_modules/@angular/core/src/errors.d.ts, line: 11` 
`[09:16:32]  typescript: node_modules/ngx-mqtt/node_modules/@angular/core/src/errors.d.ts, line: 12` 
`[09:16:32]  typescript: node_modules/ngx-mqtt/node_modules/@angular/core/src/errors.d.ts, line: 13` 

`       L9:  export declare function getOriginalError(error: Error): Error;`
`      L10:  export declare function getErrorLogger(error: Error): (console: Console, ...values: any[]) => void;`

`            Initializers are not allowed in ambient contexts. `

`      L10:  export declare function getErrorLogger(error: Error): (console: Console, ...values: any[]) => void;`

`            Initializers are not allowed in ambient contexts. `

`            Initializers are not allowed in ambient contexts. `

`this.myOtherMessage$ = this._mqttService.observe('my/other/topic');`
`[ts]
Type 'Observable<MqttMessage>' is not assignable to type 'Observable<MqttMessage>'. Two different types with this name exist, but they are unrelated.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.`

can you help me fix these issues?

**Comment by sclausen** [comment]
Wow, that was a very fast response on a recent change.
Your problem is, that I used the last rc of angular 4 and ionic 2 and it's dependencies versions lack behind.
I'll dig into problem this tomorrow.

**Comment by sclausen** [comment]
I built a new version and hope my changes will fix your problem. do you mind to try and tell me, if it works?

**Comment by dimpu** [comment]
I have the same issue.

my package.json

 "dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic-native/core": "3.1.0",
    "@ionic-native/file": "^3.4.3",
    "@ionic-native/splash-screen": "3.1.0",
    "@ionic-native/status-bar": "3.1.0",
    "@ionic-native/transfer": "^3.4.3",
    "@ionic-native/youtube-video-player": "^3.4.3",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.3.0",
    "ionic-audio": "^2.3.4",
    "ionic-native": "^2.9.0",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "videojs-youtube": "^2.3.2",
    "web-animations-js": "^2.2.2",
    "youtube-player": "^4.2.3",
    "youtube-search": "^1.0.9",
    "zone.js": "0.7.2"
  },

**Comment by sclausen** [comment]
@dimpu I'm missing the version of `angular2-mqtt` or `ngx-mqtt` in your package.json, which version do you use?

**Comment by sclausen** [comment]
I'm closing this issue, since no one could provide helpful information as a basis to start investigating your issue.
[I've set up a repository](https://github.com/sclausen/ngx-mqtt-ionic-test) and using `ngx-mqtt` with `ionic` works like a charm for me.
If anyone encounters any problems with ngx-mqtt in ionic, please open another issue.

**Comment by dimpu** [comment]
@sclausen Thank you much for your help. My issue resolved by updating ionic. With your suggested solution it didn't work for me.

**Comment by sclausen** [comment]
@dimpu thanks for the feedback. What exactly didn't worked? [The repository](https://github.com/sclausen/ngx-mqtt-ionic-test) I provided?

**Comment by dimpu** [comment]
No I have added `ngx-mqtt` to my project. It didn't worked for me. I have not tired your repo.

**Comment by dimpu** [comment]
I'm using ionic3 now its working perfectly. In fact I feel its very fast compare to ionic 2.

**Comment by imphat** [comment]
Sorry for the delay, I've tested and the sample provided works just fine.
