### ISSUE TITLE
Set the config options at runtime 

### ISSUE THREAD

**Issue by simontol** [sclausen/ngx-mqtt#132]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior
Is it possible to set the config at runtime?
I'm not able to retrieve the host and other settings when the app is started but I have to retrieve them later with a REST call.

## Expected behavior
I wish that I could pass config parameters at component or service level.

## Environment

<pre><code>
ngx-mqtt version: 6.9.0

**Comment by sclausen** [comment]
You can set `connectOnCreate` to false in the options where you import the `MqttModule` and then later do a manual `connect` on the service with your retrieved options.
