### ISSUE TITLE
Use with already created mqqt.Client instance

### ISSUE THREAD

**Issue by tgjorgoski** [sclausen/ngx-mqtt#14]
Hi, I already have a wrapper for mqtt.Client class, so I create the instance of that class separately.
Is it possible to have a constructor which would take already created mqtt.Client?

**Comment by sclausen** [comment]
not yet

**Comment by sclausen** [comment]
But now. I would be happy, if you could tell me if it suits your needs, or if there is something to improve.

**Comment by sclausen** [comment]
Now you can pass the `MQTT.js` client either as the second parameter in the service factory, or in the `connect` method.
I hope this suits your needs and would be happy, if you could provide feedback.

**Comment by tgjorgoski** [comment]
Wow, that was fast! I will try to integrate the library in my project now.
