### ISSUE TITLE
Make port & path optional on url

### ISSUE THREAD

**Issue by Therealnaxos** [sclausen/ngx-mqtt#143]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior

Cannot connect to AWS MQTT with presigned MQTT URL broker due to `path` & `port` not being optional.
Produces 403 error.

How URL should look `"wss://xxxxxxxx/`
How it looks in ngx-mqtt: `"wss://xxxxxxxx:1884//`
(note default port & double slashes)

## What is the motivation / use case for changing the behavior?

Some brokers won't accept port and/or double slashes in end of url.
Make them optional.
___
**Simple suggestion - No breaking change**
Maybe new flag in `IMqttServiceOptions` interface, `mqtt.model.ts, line: 91`
```javascript
export interface IMqttServiceOptions extends IClientOptions {
  /** wether a new connection should be created
   *  on creating an instance of the service */
  connectOnCreate?: boolean;
  /** the hostname of the mqtt broker */
  hostname?: string;
  /** the port to connect with websocket to the broker */
  port?: number;
  /** the path parameters to connect to e.g. `/mqtt` */
  path?: string;
  protocol?: 'wss' | 'ws';
  /** if your mqtt broker won't accept port and path */
  noPortAndPath?: boolean
}
```

And in `connect` function, `mqtt.service.ts, line: 97`

```javascript
    if (options.noPortAndPath) {
      this._url = `${protocol}://${hostname}`;
    } else {
      this._url = `${protocol}://${hostname}:${port}/${path}`;
    }
```

## Environment

<pre><code>
ngx-mqtt version: 6.11.0

- Broker: AWS IoT

Others:

</code></pre>

**Comment by Therealnaxos** [comment]
Edit: suggestion above isn't enough. `mergedOptions` that extends `options` also seem to add, ":443", in end of url.

**Comment by sclausen** [comment]
I'm not entirely good with your solution, but your issue is totally valid and I'll adjust the port and path handling tomorrow!

**Comment by Therealnaxos** [comment]
Yes my "solution", was kind of desperate. But I'm glad I got my point across. Thank you Sebastian. ❤️

**Comment by psrivastava-rsc** [comment]
Is this solved? Im facing similar problem

**Comment by sclausen** [comment]
`port` and `path` are optional in the [model](https://github.com/sclausen/ngx-mqtt/blob/a308d718d30316a4503d4d79a0657b165553d163/projects/ngx-mqtt/src/lib/mqtt.model.ts#L19-L21) and the code only appends a port and path if it exists [here](
https://github.com/sclausen/ngx-mqtt/blob/a308d718d30316a4503d4d79a0657b165553d163/projects/ngx-mqtt/src/lib/mqtt.service.ts#L179-L180).
Could you please post a minimal working example of your code, so I can see what the issue is?

**Comment by guuurris** [comment]
I have also notice that the code adds a port to the url string. For protocol **wss** it automatically adds **:443** and for **ws** it adds **:80**

e.g. 

**For configuration:**

```
  iMqttServiceOptions: IMqttServiceOptions = {
    hostname: 'localhost',
    path: '',
    username: 'app',
    clientId: '<uuid>',
    protocol: 'wss',
    connectOnCreate: true
  };

```
**It connects to url:** wss://localhost:443

**Comment by sclausen** [comment]
@guuurris could you please post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I don’t see where the port is automatically added by default.

**Comment by guuurris** [comment]
@sclausen I can probably reproduce it if there is some demo app that is available to fork.

**Comment by sclausen** [comment]
@guuurris don‘t play the UNO reverse card to me.
