### ISSUE TITLE
Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by gurelsoycaner** [sclausen/ngx-mqtt#146]
Hi,

I'm getting the below error trying to connect to my MQTT broker.

mqtt.min.js:1 WebSocket connection to 'ws://a2.pr14.bakelor.com:1883/' failed: Connection closed before receiving a handshake response

I'm using angular 8 and below is my configurations:-

export const MQTT_SERVICE_OPTIONS: IMqttServiceOptions = {
  hostname: 'a2.pr14.bakelor.com',
  connectOnCreate: true,
  port: 1883,
  protocol: 'ws',
  username: 'xxxx',
  password: 'xxxxx'
};

please a little assistance needed.

look forward to hearing from you.
thanks in advance.

**Comment by sclausen** [comment]
By default `1883` is the tcp port of a mqtt broker.

Here is an excerpt of the manual at https://sclausen.github.io/ngx-mqtt/#important-note:
> Since most of the opened issues here are caused by misconfiguration, please make sure your broker listens on websockets and you’ve configured the right port for it.

**Comment by gurelsoycaner** [comment]
H,
Thanks for replying this fast,
My configurations are base on the example from your link
https://sclausen.github.io/ngx-mqtt/#important-note
and I've also tested that my MQTT broker is working by using a program from https://mqttfx.jensd.de

Please I need help.

**Comment by sclausen** [comment]
You're not exactly following my example. You're not using the websocket port, but the tcp port of the broker.
The desktop application you downloaded also uses the tcp port which does not work in the browser.
It **has** to be the websocket port!

**Comment by gurelsoycaner** [comment]
thanks for your support
