### ISSUE TITLE
qos of undefined after connection successfull

### ISSUE THREAD

**Issue by mustafakunwa** [sclausen/ngx-mqtt#147]
- [ ] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Current behavior
After the connection was established I'm getting this error message after which none of  my subscription works, I'm using MQTT-spy & HiveMQ to publish or receive data there it works as expected but on the web, I get this Issue as soon as try to observe it gets the error

## Expected behavior
After Connection established it should not through error and i must observe where I'm subscribing

## Environment

<pre><code>
ngx-mqtt version: 6.13.2

</code></pre>
mqtt.min.js:formatted:1 ERROR TypeError: Cannot set property 'qos' of undefined
![image](https://user-images.githubusercontent.com/45129618/73511851-3dc7f680-440d-11ea-857a-9ef3daead840.png)

**Comment by sclausen** [comment]
Would you be so kind and follow the issue template? I need a reproduction of your issue, this is unfortunately too vague.

**Comment by sclausen** [comment]
The [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) is still missing.
Based upon the error message, I can't even guess what's wrong.

**Comment by sclausen** [comment]
Without providing a proper amount of information, I can‘t help.
