### ISSUE TITLE
angular4 support

### ISSUE THREAD

**Issue by ramarro123** [sclausen/ngx-mqtt#15]
Hi,

can you pls add support for angular4 on npm?

it's just matter of changing the dependency version or relax the checks as i just get a little warn (but the code still work)

**Comment by sclausen** [comment]
Which version do you use? The last version of ngx-mqtt should I deed Support angular4

**Comment by ramarro123** [comment]
umm, i think that i am using ng2-mqtt 
did u renamed it? i miss it :D sorry

**Comment by ramarro123** [comment]
yup,worked!
