### ISSUE TITLE
Script or instructions to build vendor/mqtt.min.js

### ISSUE THREAD

**Issue by leolara** [sclausen/ngx-mqtt#150]
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [X] Feature request

## Current behavior
The dependency file vendor/mqtt.min.js is statically added to the project

## Expected behavior
A script or instructions for building that dependency

## Minimal reproduction of the problem with instructions
irrelevant

## What is the motivation / use case for changing the behavior?

For me personally, I am trying to use mqtt.js in a browser project, but I only get it to work with your version, otherwise it gives me an error that `global` does not exists.

In general, I think it is good for security reasons to know where all deps come from

## Environment

<pre><code>
ngx-mqtt version: latest stable

- Broker irrelevant

</code></pre>

**Comment by sclausen** [comment]
It's from [here](https://unpkg.com/mqtt@3.0.0/dist/mqtt.min.js)

**Comment by leolara** [comment]
Thanks, I guess that is produced by mqtt.js project, I will see their build system to see how they made it. I simply installed with yarn mqtt and it didn't work in the browser

**Comment by sclausen** [comment]
Yes, they have a build script in their project to produce a bundle targeting the browser. It’s the `browser-build` script in their `package.json`. Unfortunately no way I tried felt right creating the bundle in a build script in this project so I went this way.

**Comment by leolara** [comment]
Thanks
