### ISSUE TITLE
Can we get Changelog please?

### ISSUE THREAD

**Issue by saranglakare** [sclausen/ngx-mqtt#154]
Hi,

First of all, thanks for this amazing library!

This is just a request to provide Changelog with every release so we can update this library regularly.

I see last ChangeLog for `6.13.3` whereas npm shows `7.0.0` is available - but I cannot find ChangeLog.

Thanks!

**Comment by sclausen** [comment]
A changelog will be added with merging PR #153

**Comment by sclausen** [comment]
done with merging PR #153
