### ISSUE TITLE
Cannot find module 'ngx-mqtt'

### ISSUE THREAD

**Issue by cmargulhano** [sclausen/ngx-mqtt#155]
After install:
`npm i ngx-mqtt`

Cannot find module 'ngx-mqtt'

![image](https://user-images.githubusercontent.com/11628058/89820324-39e70080-db23-11ea-8b53-ae6c631c8657.png)

**Comment by chadhutchins182** [comment]
Same is happening to me. I deleted my node_modules folder and ran `npm i` again just to make sure.

VSCode says:

`Cannot find module 'ngx-mqtt' or its corresponding type declarations.ts(2307)`

**Comment by minicatsCB** [comment]
What version have you installed?

For me, doing `npm i ngx-mqtt` installed version 7.0.0 (last version in NPM at the time) and I was getting that same error. I downgraded to [6.13.3](https://github.com/sclausen/ngx-mqtt/releases/tag/v6.13.3) (last version in the repo at the time) and the error dissapeared.

**Comment by sclausen** [comment]
The `7.x` versions are all broken, since the transition to angular-lib wasn't as smooth as expected. Please stay tuned. This particular error is fixed in `7.0.9`, but as of issues with `mqtt.js`, `ngx-mqtt` is still unusable.
