### ISSUE TITLE
Set CONNECTING state when calling connect()

### ISSUE THREAD

**Issue by trojanc** [sclausen/ngx-mqtt#16]
Hi

The problem I have is I have a directive that gets repeated many times, each using the mqttService to subscribe for its topic, and unsubscribe when destroyed. I wanted to check the `state` property of the service to avoid each directive attempting to create another connection. But the `state` is `CLOSED` and only changes to `CONNECTED` once a connection to the MQTT server is made.

I'd think it would help if the `state` could be `CONNECTING` as soon as `connect()` is called. This way anything trying to use the service can correctly check that the service is already attempting to make a connection (because the directives gets created faster than the service connects to the MQTT server)

You can see my [commit](https://github.com/trojanc/ngx-mqtt/commit/cd42ab488b8d12b71a43d97222a49ac9fd1ae868), I THINK this should have the state set properly.

_I've tried to fix this myself and make a pull request, but I couldn't manage to get a clean clone to run...so I can't really try and fix it. Maybe give some small doc how to build and test locally would help too :)_

**Comment by sclausen** [comment]
That's a really interesting issue. I'll catch up on that within a few days.

**Comment by sclausen** [comment]
@trojanc Many thanks for pointing this mistake out.

**Comment by sclausen** [comment]
@trojanc the latest commit adds a little documentation how to run the demo and build the library.
If you have any questions, please let me know.

**Comment by trojanc** [comment]
Great stuff thank you!
I'm doing a project that is going to rely a lot on this library, so hopefully I can share some updates/fixes soon. Great work on the library thus far
