### ISSUE TITLE
Using MQTT v5 "properties" in messages...

### ISSUE THREAD

**Issue by PaulMoore-PaymentsFoundry** [sclausen/ngx-mqtt#160]
Apologies for the seemingly daft question, but perhaps I'm missing something...

- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request

Can't add "properties" options to message publish options...

## Expected behavior
Should be able to specify qos, retain, dup and properties (v5 only)

## Minimal reproduction of the problem with instructions
await this._mqttService.unsafePublish("testTopic", "blah", {qos: 1, properties: {messageExpiryInterval: 10}})

## Environment

<pre><code>
ngx-mqtt version: 7.0.9

- Broker VerneMQ

Others:

</code></pre>

**Comment by sclausen** [comment]
`mqtt.js@4.2.0`, [has just added support](https://github.com/mqttjs/MQTT.js/releases/tag/v4.2.0) for the properties field. I made a new publication `ngx-mqtt@7.0.13` with the updated dependency.
