### ISSUE TITLE
No provider for MqttService

### ISSUE THREAD

**Issue by imphat** [sclausen/ngx-mqtt#17]
Hello again. I've been playing a bit with this great lib and found an odd situation. Since I am learning typescript, angular and ionic at the same time, I am probably missing something and do appreciate any help. 

I've created new Ionic 3 project and added the MqttService as a singleton: 

```
imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    })
  ],
```

This works great on MyApp component and I can subscribe to topics just fine. 

```
export class MyApp {
  @ViewChild(Nav) nav;
  constructor(platform: Platform, private _mqttService: MqttService) {
    platform.ready().then(() => {
      _mqttService.observe('pages').subscribe((message: MqttMessage) => {
          if(message.payload.toString() == 'contacts') {
            this.nav.push(ContactsPage);

``` 

But when I try to inject the service into another component, I get a No provider for MqttService error. 
```
@Component {...}
export class MonitorPage {
  constructor(private _mqtt: MqttService) {
  }
...

```

Shouldn't the forRoot method automatically inject MqttService for any module in the application?

**Comment by sclausen** [comment]
Yes, it should. If you use lazy routes though, it doesn't. Then you have to import `MqttModule` (without calling `forRoot`)
Could you provide an example repository for me to dig into this?

**Comment by imphat** [comment]
Thanks for the help! Here it goes: [ngx-mqtt-ionic-samples](https://github.com/imphat/ngx-mqtt-ionic-samples)

**Comment by sclausen** [comment]
Okay ionic evolved over the time since I last had worked with it. As I can see, the way how ionic 3 handles modules is different from normal ngx apps and you're not the only one struggling with this topic. I'm sorry, but I still need more time to investigate this issue.

**Comment by sclausen** [comment]
@imphat It's not working, because your imports are wrong in every component, except home. You have to import `MqttService`, `MqttMessage` and so on from `ngx-mqtt` and not `ngx-mqtt/src`.

**Comment by imphat** [comment]
@sclausen thanks a lot, it is working properly after the suggested change. 

I failed to note the wrong import since it was automatically filled by vscode. ;/
