### ISSUE TITLE
ngx-mqtt does not install in Angualr 10.2.3

### ISSUE THREAD

**Issue by vahidx4876** [sclausen/ngx-mqtt#171]
Hi,
ngx-mqtt does not install in Angualr 10.2.3 my config as flow blow: 
os : windows 10 x64
npm:6.14.8
node:  14.15.0
Angular : 10.2.3
Thanks

**Comment by pinkmadkitten** [comment]
I managed to install v8.0.1 using following steps:

1.  create `.npmrc` file near your `package.json`
2.  add `MQTT_DISABLE_HOOK=true` there & save

**Comment by vahidx4876** [comment]
I created, But I can not get install the Mqtt package on v8.0.1 work on 7.0.14 version for yet 
![mqtt](https://user-images.githubusercontent.com/38850410/102696782-2290f000-4246-11eb-92b3-88e2bfb9e193.PNG)

**Comment by sclausen** [comment]
Could you please post your actual debug.log?
This *may* have been solved with the releaes of v8.0.3. Can you confirm this?

**Comment by vahidx4876** [comment]
Yes, sure the file attached with this post 
[2021-01-08T20_01_01_625Z-debug.log](https://github.com/sclausen/ngx-mqtt/files/5789167/2021-01-08T20_01_01_625Z-debug.log)

**Comment by tgangso** [comment]
Same issue, any update?

**Comment by turtletramp** [comment]
I just create a fresh angular project with latest Angular version (11.2.0).

when installing with `npm install ngx-mqtt@8.0.1 --save` it just **works**.

when I install latest version with `npm install ngx-mqtt --save` it **fails** and I get the same error as  @vahidx4876 (I think).

In the terminal I see this error (which is missing in the above screenshot):
```
> ngx-mqtt@8.0.3 postinstall /home/thomas/git/freelancing/SensorCard/web/SensorCardUI/node_modules/ngx-mqtt
> node postinstall

[Error: ENOENT: no such file or directory, open '../../node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../../node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'
}
/home/thomas/git/freelancing/SensorCard/web/SensorCardUI/node_modules/ngx-mqtt/postinstall.js:33
    throw err;
    ^

[Error: ENOENT: no such file or directory, open '../../node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../../node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-mqtt@8.0.3 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-mqtt@8.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I also can confirm that the path `../../node_modules/@angular-devkit/build-angular/src/angular-cli-files` simply does not exist.

**Comment by sclausen** [comment]
The issue should be resolved with the latest version. Can you confirm?
