### ISSUE TITLE
Still using Angular 9 in peer dependencies

### ISSUE THREAD

**Issue by pinkmadkitten** [sclausen/ngx-mqtt#172]
https://github.com/sclausen/ngx-mqtt/blob/be7c50169115f01804296d85f0485e63d68174b0/projects/ngx-mqtt/package.json#L8-L9

**Comment by sclausen** [comment]
Yes, that’s right for 8.0.1, but in the master, for 8.0.2 it’s fixed.

**Comment by pinkmadkitten** [comment]
@sclausen so when will you release it? Latest available is still 8.0.1 
And it looks like you're missing version for Angular 10 - 8.0.1 has Angular 9 as peer dependency & 8.0.2 has jumped to Angular 11
