### ISSUE TITLE
The JS path for angular <11 browser.js is wrong

### ISSUE THREAD

**Issue by Anberm** [sclausen/ngx-mqtt#173]
- [ ] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Current behavior

ng11 browser path：‘../../node_modules/@angular-devkit/build-angular/src/webpack/configs/browser.js‘
ng10 browser path：‘../../node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js‘

## Environment

<pre><code>
ngx-mqtt version: X.Y.Z

- Broker 

Others:

</code></pre>

**Comment by ccravens** [comment]
I can confirm this issue for me as well, in order to update to `8.0.1` I had to first upgrade from angular 10 -> angular 11 with `--force`, then I had to update ngx-mqtt

**Comment by sclausen** [comment]
This issue should be done with the merge of #174 and the release of v8.0.3
