### ISSUE TITLE
Import MqttModule Problem Angular 11

### ISSUE THREAD

**Issue by CarlosOliverHM** [sclausen/ngx-mqtt#179]
## Current behavior
When I add `MqttModule.forRoot(MQTT_SERVICE_OPTIONS)` in app.module.ts I get:

![Captura de Pantalla 2021-02-13 a la(s) 20 47 08](https://user-images.githubusercontent.com/69133284/107867008-a5948800-6e3c-11eb-9350-6fb62bae75da.png)

## Expected behavior
No problems in localhost:4200

## Environment

```
import { IMqttServiceOptions, MqttModule} from "ngx-mqtt";
import { environment as env } from '../environments/environment';

const MQTT_SERVICE_OPTIONS: IMqttServiceOptions = {
  hostname: env.mqtt.server,
  port: env.mqtt.port,
  protocol: (env.mqtt.protocol === "wss") ? "wss" : "ws",
  path: '',
};

imports: [
    ...
    MqttModule.forRoot(MQTT_SERVICE_OPTIONS),
   ...
  ],
```

ngx-mqtt version: 7.0.9

It is not possible to install the new version in Angular 11, because has the problem of Angular 11 compatibility with ngx-mqtt #17 issue.
![Captura de Pantalla 2021-02-13 a la(s) 20 51 47](https://user-images.githubusercontent.com/69133284/107867096-4d11ba80-6e3d-11eb-8564-e61ae6d61ce2.png)

<img width="496" alt="Captura de Pantalla 2021-02-13 a la(s) 20 52 08" src="https://user-images.githubusercontent.com/69133284/107867102-5bf86d00-6e3d-11eb-8acf-28c20c6cde25.png">

**Comment by sclausen** [comment]
Duplicated by #170
