### ISSUE TITLE
Question on Websocket Connection Behavior

### ISSUE THREAD

**Issue by ccravens** [sclausen/ngx-mqtt#183]
- [X] **I have searched for similar issues in this repository, but couldn't find one.**
- [X] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request
- [X] Question

## Current behavior
I'm not submitting an issue, but more-so a question on websocket and mqtt behavior to make sure the behavior is correct. I'm attaching a screenshot below of network traffic for 2 websocket services running together. `services` is a non-mqtt websocket connection and `ws` is the ngx-mqtt websocket connection. As you can see the, `services` connection stays in the `Pending` state while the ngx-mqtt connection reconnects every minute. Because this is MQTT over websockets is this expected behavior? Do we only want to maintain one websocket connection persisted for the entire user session. Also I'm not sure right now if this is due to ngx-mqtt client-side configurations or maybe something server-side?

Either way not a big deal but just a question I had was hoping to get some clarification on thank you!

![image](https://user-images.githubusercontent.com/1319049/118405718-00f63200-b647-11eb-8a12-adc5154e17e3.png)

## Environment

<pre><code>
ngx-mqtt version: 8.0.1

- Broker: Aedes (https://github.com/moscajs/aedes)

Others:
Angular 11.0.0
</code></pre>

**Comment by sclausen** [comment]
Oh, I thought I had answered you. Sorry, I forgot.
The internal websocket and connection handling is managed by [MQTT.js](https://github.com/mqttjs/MQTT.js) and not by this library. I would suggest you ask this question in their issue tracker.

**Comment by sclausen** [comment]
I think what you're searching is the `keepalive` you want to set to `0` in the options
https://github.com/mqttjs/MQTT.js/blob/master/README.md#mqttclientstreambuilder-options

**Comment by ccravens** [comment]
@sclausen just tested and YES! Seems like that's exactly what solved my problem! Thank you! 💯  🥇
