### ISSUE TITLE
Some messages are delayed when subscribing to many topics (>20 topics)

### ISSUE THREAD

**Issue by ldkid12** [sclausen/ngx-mqtt#187]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request

## Current behavior

Payload values from messages (subscribed topics - not retained) are updated correctly if ~20 topics are subscribed. Any subscriptions more than that (say 40), there are noticeable delay in the value update. The observable is not emitting the current value but previous values over time (skipped over time).

![mqtt-service-issue](https://user-images.githubusercontent.com/44103188/121442457-97fd9380-c940-11eb-8482-feb7e8357be0.jpg)

## Expected behavior

messages from subscribed topics should be consistently updated regardless of how many topics.

## Minimal working example
```typescript (Component)
// Component
import { Component, OnDestroy } from '@angular/core';
import { MqttService } from 'ngx-mqtt';
import { Observable, Subject } from 'rxjs';
import { map, takeUntil } from 'rxjs/operators';

interface TopicData {
  topic: string;
  payload?: Observable<number> | Observable<string> | undefined;
}

const TOPICS: TopicData[] = [
  {topic: '$SYS/broker/uptime'},
  {topic: '$SYS/broker/clients/total'},
  {topic: '$SYS/broker/clients/maximum'},
  {topic: '$SYS/broker/clients/inactive'},
  {topic: '$SYS/broker/clients/disconnected'},
  {topic: '$SYS/broker/clients/active'},
  {topic: '$SYS/broker/clients/connected'},
  {topic: '$SYS/broker/clients/expired'},
  {topic: '$SYS/broker/messages/stored'},
  {topic: '$SYS/broker/messages/received'},
  {topic: '$SYS/broker/messages/sent'},
  {topic: '$SYS/broker/subscriptions/count'},
  {topic: '$SYS/broker/retained messages/count'},
  {topic: '$SYS/broker/publish/messages/dropped'},
  {topic: '$SYS/broker/publish/messages/received'},
  {topic: '$SYS/broker/publish/messages/sent'},
  {topic: '$SYS/broker/publish/bytes/received'},
  {topic: '$SYS/broker/publish/bytes/sent'},
  {topic: '$SYS/broker/bytes/received'},
  {topic: '$SYS/broker/bytes/sent'},
  {topic: '$SYS/broker/load/messages/received/1min'},
  {topic: '$SYS/broker/load/messages/received/5min'},
  {topic: '$SYS/broker/load/messages/received/15min'},
  {topic: '$SYS/broker/load/messages/sent/1min'},
  {topic: '$SYS/broker/load/messages/sent/5min'},
  {topic: '$SYS/broker/load/messages/sent/15min'},
  {topic: '$SYS/broker/load/bytes/received/1min'},
  {topic: '$SYS/broker/load/bytes/received/5min'},
  {topic: '$SYS/broker/load/bytes/received/15min'},
  {topic: '$SYS/broker/load/bytes/sent/1min'},
  {topic: '$SYS/broker/load/bytes/sent/5min'},
  {topic: '$SYS/broker/load/bytes/sent/15min'},
  {topic: '$SYS/broker/load/publish/received/1min'},
  {topic: '$SYS/broker/load/publish/received/5min'},
  {topic: '$SYS/broker/load/publish/received/15min'},
  {topic: '$SYS/broker/load/publish/sent/1min'},
  {topic: '$SYS/broker/load/publish/sent/5min'},
  {topic: '$SYS/broker/load/publish/sent/15min'},
  {topic: '$SYS/broker/load/publish/dropped/1min'},
  {topic: '$SYS/broker/load/publish/dropped/5min'},
  {topic: '$SYS/broker/load/publish/dropped/15min'},
];

@Component({
  selector: 'lbd-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.scss']
})
export class FooComponent implements OnDestroy {
  private readonly onDestroy = new Subject<void>();
  topics: TopicData[] = TOPICS;

  constructor(private mqtt: MqttService) {
    this.mqtt.connect({hostname: 'localhost', port: 9001, path: '/mqtt'});
    for (const topic of TOPICS) {
      topic.payload = this.mqtt.observe(topic.topic).pipe(
        map((msg) => msg.payload.toString()),
        takeUntil(this.onDestroy),
      );
    }
  }

  ngOnDestroy() {
    this.onDestroy.next();
    this.onDestroy.complete();
  }

}
```

```html (template)
// html template
<div class="Topic General" *ngFor="let topic of topics">
    <strong>{{ topic.topic }}</strong>
    {{ topic.payload | async }}
</div>
```

## Environment

<pre><code>
ngx-mqtt version: 8.0.1
mosquitto version: 1.4.9
MQTT-Explorer version: 0.4.0-beta1

- Broker 
Mosquitto ($SYS topics) - Non retained topics are updated every 11s.

</code></pre>

**Comment by fredmorin** [comment]
Is this delayed by the ngx-mqtt library, or by your message broker?

**Comment by ldkid12** [comment]
> Is this delayed by the ngx-mqtt library, or by your message broker?

This is delayed by the nqx-mqtt library at least based on our observation during investigation.

**Comment by ldkid12** [comment]
> > Is this delayed by the ngx-mqtt library, or by your message broker?
> 
> This is delayed by the nqx-mqtt library at least based on our observation during investigation.

notice from the screenshot, the local broker (reported by MQTT explorer) is 6/9/21 4:27:15pm with the value 9:98 but the observed value in the component (using the library) of the same topic is 10.17, which in the MQTT explorer history was taken at 4:26pm, a value that is taken 66s earlier.

**Comment by sclausen** [comment]
Would you be so kind and post a mwe that is actually complete and runnable either on any platform like codesandbox.up or in a separate github repository?

**Comment by ldkid12** [comment]
> Would you be so kind and post a mwe that is actually complete and runnable either on any platform like codesandbox.up or in a separate github repository?

Hi, just created a mwe in codesandbox. 
https://codesandbox.io/s/mqtt-service-test-01f1n?file=/src/app/app.component.html
This has to connect to a local broker at the localhost. Let me know if you need anything else.

**Comment by ldkid12** [comment]
Also, the mosquitto broker we use update non-retained $SYS topics every 11sec. We also used HiveMQ Websocket client to validate. Both MQTT Explorer and HiveMQ client are in sync but not the ngx-MQTT service.

**Comment by sclausen** [comment]
Thank you very much, I'll look into it this weekend. Did you tried your usecase with plain MQTT.js too? It cannot be ruled out, the the performance issues arise from my code, though. Especially the observables might have some implications I‘m not aware of.

**Comment by sclausen** [comment]
I have to admit, that I can't see any delay you perceive in your application.
https://user-images.githubusercontent.com/916076/121746724-98478b80-cb06-11eb-835c-f1a99ef0f7d8.mov

**Comment by ldkid12** [comment]
> I have to admit, that I can't see any delay you perceive in your application.
> https://user-images.githubusercontent.com/916076/121746724-98478b80-cb06-11eb-835c-f1a99ef0f7d8.mov

Attached here are two videos. One showing the uptime (not updated until much later) and the second video shows topics not updated until much later.

https://user-images.githubusercontent.com/44103188/121751300-b55a6b00-cac2-11eb-81a1-0343e291253a.mp4


https://user-images.githubusercontent.com/44103188/121751313-bb504c00-cac2-11eb-9225-394af0ee370b.mp4

**Comment by sclausen** [comment]
I think I might found the issue. I couldn't reproduce at first, because I used `ws` in MQTT Explorer too. I couldn't use your version `1.4.9` of mosquitto though, since that version isn't available on docker hub, but I could reproduce your issues with `1.4.8` and `1.4.9`. With the latest version of mosquitto I couldn't reproduce this behaviour, so I think it's broker related and nothing regarding this library.

Could you please try to use a recent mosquitto version and try to reproduce it again?
You can execute the `mosquitt.sh` script in the root folder of the project to run the latest mosquitto. It exposes the `ws` port under `9001` and `mqtt` under `1883`.

**Comment by ldkid12** [comment]
> I think I might found the issue. I couldn't reproduce at first, because I used `ws` and the according port in MQTT Explorer too. I couldn't use your version `1.4.9` (it's 4 years old) of mosquitto though, since that version isn't available on docker hub, but I could reproduce your issues with `1.4.8` and `1.4.10` when setting MQTT Explorer to listen on the `mqtt` protocol and port. With the latest version of mosquitto I couldn't reproduce this behaviour, so I think it's broker related and nothing regarding this library.
> 
> Could you please try to use a recent mosquitto version and try to reproduce it again?
> You can execute the `mosquitto.sh` script in the root folder of the project to run the latest mosquitto. It exposes the `ws` port under `9001` and `mqtt` under `1883`.

Thanks for taking time to look into this. It looks like that is the problem. I'll do more testing. I'm still a little confused why the old version would work on MQTT explorer. In the previous version, I also set the MQTT explorer to use MQTT protocol and port 1883 and did not see the symptom.
![MQTTExplorer-ProtocolPort](https://user-images.githubusercontent.com/44103188/121967864-fef6c000-cd25-11eb-83df-71313b440b58.png)

**Comment by sclausen** [comment]
Maybe the mosquito devs screwed up the websocket part of the Broker in some versions 🤷‍♂️

**Comment by sclausen** [comment]
Yes they had performance issues in older versions.
https://github.com/eclipse/mosquitto/issues/411

**Comment by ldkid12** [comment]
Thanks again for your help.
