### ISSUE TITLE
IonErrorEvent.code not present in ngx-mqtt 9.0.5

### ISSUE THREAD

**Issue by casper5822** [sclausen/ngx-mqtt#188]
- [ ] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request

## Current behavior

Hello, i migrate to 9.0.5 and on IonErrorEvent.code not working anymore. So my question is, what is the new way

## Expected behavior

This is my code that works with the previous versions, the error is in error.code == 5 (code not found)

  this.mqtt.onError.subscribe((error) => {

          this.connected = false;
          this.mqtt.disconnect();
          this.mqttSub.unsubscribe();
          this.mqttSub2.unsubscribe();

          if(this.retryConnection <= 3){
            setTimeout(()=>{
              this.retryConnection++;
              this.initConnections();
            },this.retryConnection * 2000)
          }else if(error.code == 5 && this.retryConnection == 4){
              //token invalid, innesco refreshToken nell'interceptor con una piccola richiesta http
              this.http.get<any>(Constants.PINGER_API)
              .subscribe(
                ()=>{
                  //a questo punto la richiesta avrà access token nuovo, provo la quarta volta soltanto
                  this.initConnections();
                });
          }else{
            this.displayError();
          }
    });

## Environment

<pre><code>
ngx-mqtt version: 9.0.5

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
Would you be so kind and follow the request for a minimal working example? Here is the description of it from the issue template:
> For bug reports please provide a *MINIMAL DEMO* of the problem on https://codesandbox.io/ or in a separated github repository.
BUG REPORTS NOT HAVING A REPRODUCTION WILL FROM NOW ON IMMEDIATELY BEING CLOSED!

I know I just broke my own rule closing issues who are ignoring that requirement, but I wanted to give you a chance to help me help you.

**Comment by casper5822** [comment]
Hello Sebastian, Thank you for your respinse. I find the solution. I use error.message instead of error.code that is not present anymore. Sorry of i didn't post a working sample when i wrote this issue.
