### ISSUE TITLE
subscriptions after MqttService connect / disconnect

### ISSUE THREAD

**Issue by imphat** [sclausen/ngx-mqtt#19]
Hello again Sebastian :)

I'm having some trouble to figure out how subscriptions work when disconnecting and reconnecting. 

When I subscribe to a certain filter and there's an involuntary disconnection/reconnection (simulated by disabling/enabling my wi-fi) it seems that all subscriptions manage to resume automatically (the service also reconnects automatically). 

But when I force the reconnection by calling the disconnect() and connect() methods, while the observables state seems to hold, the subscriptions no longer work and my application stops receiving messages, but can publish new ones just fine. 

Can you please help me once again? I've created a repository with a small ionic2 sample app
https://github.com/imphat/ngx-mqtt-connection-sample

**Comment by sclausen** [comment]
Thanks to point this out. I will investigate this issue soon.

**Comment by sclausen** [comment]
I think `1.8.0` should fix your issue. Now your filters are resubscribed after you manually reset your connection.
Does this work for you?

**Comment by imphat** [comment]
Its working great now, many thanks!
