### ISSUE TITLE
Configure ngx-mqtt for using dynamic credentials

### ISSUE THREAD

**Issue by felipeb95** [sclausen/ngx-mqtt#190]
- [☑️] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ☑️] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ☑️] Feature request

## Current behavior
Hi. I want to use ngx-mqtt with credentials that I obtain from a webservice, but configuring the MqttModule in the Appmodule does not allows me doing that. I looked for a issue reported in 2017 and tried the solution but I didn't understand it well. I'm trying to replace in the Appmodule the first code with the second:

1)
`MqttModule.forRoot(MQTT_SERVICE_OPTIONS)`
2)
`MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
})`

When I try to do this I get an error because provide and useFactory are not part of the object accepted by forRoot

## Environment

<pre><code>
ngx-mqtt version: 9.0.5

**Comment by sclausen** [comment]
You can use the `connect` method of the service with the `IMqttServiceOptions` to do that. You would normally then set the option `connectOnCreate: true` in the module configuration.

**Comment by felipeb95** [comment]
thanks!
