### ISSUE TITLE
Change config after connect

### ISSUE THREAD

**Issue by poet-of-the-fall** [sclausen/ngx-mqtt#196]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior
Currently the config for the connection can not be changed/updated. 
When using a broker with token authentication, sometimes the token needs to be updated. Currently I don't see a way to do this as the config is passed in the module.

## Expected behavior
Having a possibility to update the config or some parameters in a component.

## What is the motivation / use case for changing the behavior?
Token based authentication on the broker with short token validity time or long stay on page.

## Environment

<pre><code>
ngx-mqtt version: 6.13.3

- Broker 

Others:

</code></pre>

**Comment by poet-of-the-fall** [comment]
sorry, simply using `.connect` on the service with other config does the job

**Comment by sclausen** [comment]
Duplicate of #132
