### ISSUE TITLE
Connection to mosquitto broker over TLS

### ISSUE THREAD

**Issue by beatrizaldaz** [sclausen/ngx-mqtt#20]
Good afternoon,

Which is the option to connect to mosquitto broker using SSL (TLS)?

Thanks,
Beatriz

**Comment by sclausen** [comment]
Hi Beatriz, 
you can set the option `protocol: 'wss'` and maybe `rejectUnauthorized: false` but the latter depends on your broker. 
Does this help?

**Comment by beatrizaldaz** [comment]
Its working great now, many thanks!!!!!
