### ISSUE TITLE
Broken default setup

### ISSUE THREAD

**Issue by Ceiku** [sclausen/ngx-mqtt#21]
Trying to connect to a myriad of different brokers for this:
Cloud mqtt, hivemqtt websocket client: http://www.hivemq.com/try-out/
Thinking first that one of these brokers might not support websockets and whatnot.

Love the idea of using Rxjs subscriptions which is generally a good practice for ng2, if only it worked like intended

AppModule:
```export const MQTT_SERVICE_OPTIONS = {
  hostname: 'broker.mqttdashboard.com',
  port: 8000,
  protocol: 'mqtt', // no effect, allways uses ws protocol
  path: ''
};

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}

@NgModule({
  declarations: [
    AppComponent,
    ToolbarComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

then in AppComponent:
`constructor(private mqttService: MqttService) {
       this.mqtt.observe('test/1');
}`

Now my app wont load at all, not just telling me it cannot connect to broker. Which in and by itself is unwanted behaviour. One thing is letting me know something has gone wrong, another to affect all other independent features.

Trying manually `mqttService.connect(opts);` in App component gives errors scoped error handling, and at least the remaining features loads.
(Wanted error handling behaviour, but this step is not replicated in the documentation)
Still no connectiontion but a running app.

Connecting to the broker works fine through a standard Paho.js client, not as sweet but my only solution.

**Comment by sclausen** [comment]
The protocol can not be `mqtt`, it's either `ws` or `wss`, since you're not able to connect from the browser to mqtt via tcp, but via websockets.
Here is an excerpt from the source code:
``` typescript
  /** which protocol should be used. ws and wss are supported */
  protocol?: string;
```
I should've used `'ws' | 'wss'` instead of `string` and I have to admit, that my documentation is not really existent. I will address this issue soon.
Does changing it from `mqtt` to either `ws` or `wss` helped? Keep in mind, that the broker you're using has to support websockets!

**Comment by Ceiku** [comment]
it is ws by default. `ws://broker.mqttdashboard.com`
I started trying to connect by different protocols after initial faults, it is commented out in the above code as well. 
Changing it had no effect though, still attempted the connection with `ws`, couldn't change it to `wss` either which cloudmqtt and many others require.

**Comment by sclausen** [comment]
I'm using this library with hummingbird and successfully tested it with mosquitto too.
If you use `wss`, you have to pass `rejectUnauthorized: false` as an option (It internally uses mqtt.js), but I must admit, I've never tried `wss` before and will test this tomorrow. `ws` nevertheless should've worked for you. Would you mind to give me an example repository to test this?

**Comment by Ceiku** [comment]
https://github.com/Ceiku/ReplicatedIssue_NGX

**Comment by sclausen** [comment]
Does `1.9.0` fixes your issue?

**Comment by Ceiku** [comment]
It now connects over `ws`, great! =)
But all connections remain unsafe and I didn't get `rejectUnauthorized: false` to work with `wss`, nor with username and password fields, no error/ warnings.

Using options documented here:
https://github.com/mqttjs/MQTT.js#client

And present here in provided repo:
~/node_modules/ngx-mqtt/src/mqtt.service.d.ts

Changes are pushed to the repo, and thanks for the quick replies and effort =)

**Comment by sclausen** [comment]
I'm glad you got it running! =)

**Comment by mois770** [comment]
Got a program from a programmer to use mqtt.

It is happening the same as the issue " Broken default setup #21" and the solution protocol:'ws'  didn't help, because the Broker default is also "ws://....".

What  what else is it possible to try?

I am using cloudmqtt, checked the connection with MQTTExplorer (a Ubuntu program)  and it was working well.

Thanks

**Comment by sclausen** [comment]
@mois770 please provide a reproduction in a separate repository.

**Comment by mois770** [comment]
bsd

Thanks for answering.
You can find a repository here:
https://github.com/mois770/ionicTest
Is this what you asked for?
Any more information?

Em qui, 1 de ago de 2019 às 00:46, Sebastian Clausen <
notifications@github.com> escreveu:

**Comment by sclausen** [comment]
No, that's not [what I really wanted](https://en.wikipedia.org/wiki/Minimal_working_example), that's just a snippet of the whole thing. I would have to set up a new application and so on.

Maybe we can get to the bottom of it, if you elaborate, what you meant with

> […] the solution protocol:'ws' didn't help, because the Broker default is also "ws://...."
