### ISSUE TITLE
HOW TO CONNECT TO IOT CORE AWS

### ISSUE THREAD

**Issue by matiasAS** [sclausen/ngx-mqtt#225]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [X] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Current behavior

When connecting to IoT core, it returns the following error:
![image](https://user-images.githubusercontent.com/7276332/220422383-8e9bb2a3-6471-4b51-8eb2-1ff8763003ea.png)

IMqttServiceOptions: 
![image](https://user-images.githubusercontent.com/7276332/220422736-7ea9b0d9-8f62-4f09-9521-dca8b08016ae.png)

Using paho-mqtt python connects without error

What am I doing wrong??, help me please!!

## Environment

<pre><code>
ngx-mqtt version: 9.0.5

- Frontend: Ionic6/Angular15
- @ngx-env/builder 15.0.1
- Broker: Iot Core
- Backend: django
Others:

</code></pre>

**Comment by sclausen** [comment]
Unfortunately, I have no setup to reproduce your error, nor any expertise in AWS IoT Core at all. I would recommend asking questions like this on [stackoverflow](https://stackoverflow.com/).
