### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by stefanbildl** [sclausen/ngx-mqtt#233]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior

No support for Angular 16

## Expected behavior

Support for Angular 16

**Comment by sclausen** [comment]
Can you please elaborate, why you can't run it with angular 16?

**Comment by stefanbildl** [comment]
Current dependencies in package.json:

```
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
   ....
```


Should be ^16.
Npm install wont install if you dont use --legacy-peer-deps

**Comment by sclausen** [comment]
I didn’t had any problems installing the library in a brand new angular 16 project with node 16. Which npm and nodejs version do you use?

**Comment by sclausen** [comment]
It seems that newer node versions didn't agreed to my improperly declared angular versions. I bumped it to 16.
