### ISSUE TITLE
Upgrade Angular to v17

### ISSUE THREAD

**Issue by zack9433** [sclausen/ngx-mqtt#237]
Hi,

Angular bump its version to  v17, expect to follow up 🥸

**Comment by ChristinaBayerl** [comment]
Hi @sclausen,

is there a plan from your side to support Angular v17 anytime soon? Would be really appreciated!

**Comment by sclausen** [comment]
Thanks for the feedback, I really appreciate it.
I‘ll tackle this issue this week and keep you up to date if something unexpected happens.

**Comment by ChristinaBayerl** [comment]
Thanks for the quick work 🤩 will check it out asap.
