### ISSUE TITLE
Unable to build Production (--prod) build

### ISSUE THREAD

**Issue by chaymankala** [sclausen/ngx-mqtt#25]
When I'm trying to build with --prod, this error is occurring, after installing this module. 

sudo -E ionic cordova build android --prod

Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[16:34:23]  build prod started ...
[16:34:23]  clean started ...
[16:34:23]  clean finished in 4 ms
[16:34:23]  copy started ...
[16:34:23]  ngc started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out o
f date.
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not s
upported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectab
le in /home/chaitanya/kiot_one/node_modules/angular2-mqtt/node_modules/@angular/core/src/di/metadata.d.ts, resolving sy
mbol OpaqueToken in /home/chaitanya/kiot_one/node_modules/angular2-mqtt/node_modules/@angular/core/src/di/opaque_token.
d.ts, resolving symbol OpaqueToken in /home/chaitanya/kiot_one/node_modules/angular2-mqtt/node_modules/@angular/core/sr
c/di/opaque_token.d.ts

**Comment by chaymankala** [comment]
after removing node_modules folder from this module, the issue resolved! 
You can try improving the module for angular 4.

**Comment by sclausen** [comment]
I see in you error message that you're not using `ngx-mqtt` but the old version `angular2-mqtt`.
Does this help, or what do you think I could improve for usage with "angular 4"?
