### ISSUE TITLE
Custom Client ID

### ISSUE THREAD

**Issue by xpratpa** [sclausen/ngx-mqtt#27]
How do we generate custom client ID ?

**Comment by sclausen** [comment]
I disabled manually setting the clientid. I don't know what got into me. I will enable it by setting the clientid in the connection options soon (this weekend).

**Comment by sclausen** [comment]
In fact I didn't disabled setting the clientId. You can just set it in the service options, or on connect, or you create an mqtt client for yourself and provide it in the connect options.

``` typescript
export const MQTT_SERVICE_OPTIONS = {
  clientId: 'my-custom-client-id'
};

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    })
  ],
  declarations: [MyComponent],
  providers: [],
  bootstrap: [MyComponent]
})
```

Or like this, with manuall connecting to the broker:
``` typescript
export const MQTT_SERVICE_OPTIONS = {
  connectOnCreate: false
};

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}

constructor(private _mqtt: MqttService) {
  this.mqtt.connect({host: 'localhost', port: 9001, clientId: 'my-client-id'});
}
```
In the second manually creating a connection example, you don't provide connection options, but a whole mqtt.js client:
``` typescript
import * as MQTT from 'mqtt';

constructor(private _mqtt: MqttService) {
  var client  = MQTT.connect('mqtt://test.mosquitto.org', {clientId: 'my-client-id'})
  this.mqtt.connect(false, client);
}
```

does this help?

**Comment by sclausen** [comment]
I think this should help. If you need any further information, feel free to ask.

**Comment by xpratpa** [comment]
Thanks for help . I managed to configure client ID by passing MQTT object.
