### ISSUE TITLE
How to get/parse Topic name on receive of the message?

### ISSUE THREAD

**Issue by adeelasghar88** [sclausen/ngx-mqtt#33]
Hi,

Can anyone please tell me how can I get/parse the topic name while receiving message on a topic? e.g. a message is send on this topic `10/1/test123/front_end/backend` and after receiving/subscribing message on this topic I want to extract the `test123` from topic name. NOTE: In this example `test123` is dynamic and it will change for every message.

I am using this library and want the solution using this.

**Comment by adeelasghar88** [comment]
One solution could be to send topic name in payload of the message.

**Comment by sclausen** [comment]
This issue has nothing to do with mqtt, nor this library at all, so raising an issue here isn't the right thing to do. Please post questions like this e.g. on [stackoverflow.com](https://stackoverflow.com).

---
This is a very basic and simple javascript string parsing problem: If you can make sure, this identifier is always the third topic level, you could simply split by the topic level separator `/` and extract the array element, like so
``` javascript
const name = msg.topic.split('/')[2];
```

**Comment by adeelasghar88** [comment]
I am sorry actually I didn't notice the library `MqttMessage` contains the topic name. Got the solution. Thanks and apology again. You can remove this.
