### ISSUE TITLE
Change protocol to tcp

### ISSUE THREAD

**Issue by BigSus** [sclausen/ngx-mqtt#34]
I tried to change the communication protocol:
```
export const MQTT_SERVICE_OPTIONS = {
  hostname: 'localhost',
  port: 1883,
  protocol: "tcp" //<--------------
};
```
and the following error appears when compiling:
> Type 'string' is not assignable to type '"tcp" | "wss" | "ws" | "mqtt" | "mqtts" | "ssl"'.  

I am using the version 1.11.0 of ngx-mqtt.

I am doing something wrong?

**Comment by sclausen** [comment]
The typings are from mqtt.js, which can be used in nodejs or being transpiled for the browser. ngx-mqtt is a browser project so you can't use tcp as a protocol. You have to use either wss or ws.

**Comment by BigSus** [comment]
Ok, sorry for the inconvenience.

**Comment by sclausen** [comment]
No inconvenience at all. You have been misleaded by the typings for options. They inherit from mqtt.js, so I think I will remove this inheritance and manually add only valid options. I'll do it in  #35
