### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by benydc** [sclausen/ngx-mqtt#36]
Hi,

Is there any error handling for this module?

I would like to catch the errors when there is no network. 

Ben

**Comment by sclausen** [comment]
The service has a few `EventEmitter` getters. I think you need `onClose` and/or `onError`.
You can build the documentation with
```sh
npm i              # install all dependencies
npm run docs       # build the documentation
npm run serve:docs # open a local webserver serving the documentation
```

**Comment by sclausen** [comment]
I think this information was, what you need. Otherwise, feel free to open a fresh issue.
