### ISSUE TITLE
resume mqtt after sleep

### ISSUE THREAD

**Issue by ramarro123** [sclausen/ngx-mqtt#37]
That's a "difficult" topic, i always had problem with that things before....

long story short.

on osx (to be confirmed on other platform) when i suspend/resume -and on mac it happen quite often exp on laptop with power saving on ram-
mqtt stop to work. it doesn't try to reconnect, doesn't do anything, websocket it's still "opened" but nothing else happen.

backend it's mosquitto (version 1.4.10 probably, i am deploying on heroku right now) but it happen on my local mosquitto too (1.4.6)

i had some problem with mosquitto and auth before, so it worth to mention my broker version, in case it's related to that.

regards

**Comment by sclausen** [comment]
Would you please post the configuration of ngx-mqtt?

**Comment by ramarro123** [comment]
this.mqtt = new MqttService({
      hostname: 'm20.cloudmqtt.com',
      port: 37105,
      path: '/',
      protocol: 'wss',
      username: user,
      password: pwd,
      connectOnCreate: false
    });
some code

    this.mqtt.connect();

**Comment by sclausen** [comment]
Everything seems to be okay, if I connect to a remote mqtt broker, switch into standby and wake up again.
I don't know how your broker behaves, but the client tries to reconnect and succeeds.

**Comment by sclausen** [comment]
not reproducible
