### ISSUE TITLE
Can you provide a way to access clientId variable in MqttService class?

### ISSUE THREAD

**Issue by ygpark2** [sclausen/ngx-mqtt#38]
Hi.

First of all, I deeply appreciate your effort to make such a nice library for mqtt protocol available for everyone.

I am fully enjoying your code in my angular application.

But one thing I miss in using your library is that there is no way to access the clientId variable. In my application, I need to know the clientId for the current user who make a connection to mqtt broker. But this is not possible in your library as the clientId is set as a private. Thus please provide a function to access clientId or change the attribute from private to public.

Hopefully, my feature request is reflected in your next version.

Thank you.

**Comment by sclausen** [comment]
Thanks for your appreciation. d3528a7805cfc58381a2035328093d4cd92456ca and the accompanied version [1.13.0](/sclausen/ngx-mqtt/releases/tag/1.13.0) should fix your problem.
`clientId` is now exposed via a getter.

**Comment by sclausen** [comment]
I assume this was what you needed. Otherwise, feel free to ask, or file a new issue.

**Comment by cedricve** [comment]
@sclausen, I was wondering how do you set the client id. In the example in the readme it should be hardcoded in the factory class. Any way to make this more dynamic?

Thanks @sclausen, love your work!!

**Comment by sclausen** [comment]
The `clientId` is required on connecting to the broker, so you have to postpone this step. 
You can set `connectOnCreate: false` in the `IMqttClientOptions` you use for the factory in `MqttModule.forRoot` and then you can connect in another service or in a component with
``` typescript
public connect(opts?: IMqttServiceOptions, client?: IMqttClient);
```
There you can pass, beside all required other options, your desired `clientId`.

**Comment by sclausen** [comment]
@cedricve 
The `clientId` is required on connecting to the broker, so you have to postpone this step. 
You can set `connectOnCreate: false` in the `IMqttClientOptions` you use for the factory in `MqttModule.forRoot` and then you can connect in another service or in a component with
``` typescript
public connect(opts?: IMqttServiceOptions, client?: IMqttClient);
```
There you can pass, beside all required other options, your desired `clientId`.

**Comment by cedricve** [comment]
thanks!
