### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by andresg747** [sclausen/ngx-mqtt#40]
## Environment
<pre><code>
ngx-mqtt version: 1.13.0

- Broker: io.adafruit.com
</code></pre>

Hi. I'm trying to connect this library inside of my ionic project with the broker previously mentioned, provided by Adafruit. In their [mqtt documentation](https://learn.adafruit.com/adafruit-io/mqtt-api) they say I just need this four parameters to connect:
<pre><code>
Host: io.adafruit.com
Port: 1883 or 8883 (for SSL encrypted connection)
Username: your Adafruit account username
Password: your Adafruit IO key (click the AIO Key button on a dashboard to find the key)
</code></pre>

I don't know if it is possible to set the **username** and **password** strings in this library. I'm asking because I don't see any reference in the docs and I've tried a lot but always get this console error: 
<pre><code>
WebSocket connection to 'ws://io.adafruit.com:1883//' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
</code></pre>

I'm not an advanced developer or anything. I'm just trying to do some cool things with an IOT project. Any help would be very appreciated. Thanks in advance.

**Comment by sclausen** [comment]
`MqttServiceOptions` extends `MQTT.IClientOptions` and this interface provides `username` and `password`. I don't know which IDE you use, but the linter should be okay with it.
One thing you **maybe** got wrong is the misconception that connecting to a broker works the same on a server and a browser. You want to connect via browser to a broker which is only possible via websockets. Port 1883 and 8883 are **usually** mqtt tcp ports. Your broker has to provide a websocket endpoint, which is usually on a different port. 
I would suggest you to first try it with mosquitto. Another guy got that wrong too, here is the issue with the mosquitto configuration for websockets [#12](github.com/sclausen/ngx-mqtt/issues/12#issuecomment-285111325)

**Comment by sclausen** [comment]
I think this fiddle https://jsfiddle.net/4wwhu2o6/ should help in your case using adafruit.

**Comment by andresg747** [comment]
Hello!, I'm sorry for the late response. Thank you very much!

That's exactly what I needed, and as you said the correct URL was: "wss://io.adafruit.com:443/mqtt/"
Thanks again for the fast and accurate reply. 

I'll leave this thread for future help to others.
