### ISSUE TITLE
Any method/way to know if client subscribed to the topic successfully ?

### ISSUE THREAD

**Issue by arihantdaga** [sclausen/ngx-mqtt#41]
I am working with an application, where topics are sometimes dynamic, so I need to know whether a client could successfully subscribe to the topic or not. 
In another libraries in C++ on my device i have this confirmation. And i checked MQTT.js as well it supports a callback on subscription, wouldn't it be great to have one event emitter or any way to ensure that client has subscribed to the topic successfully.. ?

**Comment by sclausen** [comment]
The next time, please use the issue template.

Could you please explain, what you mean with "successfully subscribed"?
Do you mean emitting the `suback` message?

**Comment by arihantdaga** [comment]
@sclausen I am sorry for not using template, i'll take care next time. 
For this problem - 
When a client tries to subscribe a topic. Sometimes it is subscribed, sometimes broker may deny it and also sometime it may take some time for the confirmation of subscription. Therefore i was hoping for an event which can be used for assurance than the client is subscribed now.

**Comment by sclausen** [comment]
Brand new `1.14.0` has an onSuback field to subscribe on. I didn't exactly knew, what you wanted, but even if not, that should have been implemented anyway :wink: 
Does this help?

**Comment by arihantdaga** [comment]
Wow.. 😁
Thank you.
