### ISSUE TITLE
Use mqtt/mqtts as protocol instead of ws/wss??

### ISSUE THREAD

**Issue by jmpmscorp** [sclausen/ngx-mqtt#42]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the motivation / use case for changing the behavior?

I'm building an Ionic 2/3 app. This app has a MQTT connection. With your library, I can stablish this connection through websocket without problems but I'm looking for a way to stablish it using "mqtt:// or mqtts://" directly. I have read that you have disabled mqtt/mqtts as allowed protocol because they can't be used over web browsers as they only allow sockets over 80 and 443 ports. But, if I'm not wrong, I suppose that a mobile could do. As your library is based on MQTT.js, would be there any posibility to use mqtt/mqtts as connection protocol?

Thank you very much for your work and your time, :)
Bye.

## Environment

<pre><code>
ngx-mqtt version: 1.14.0

- Broker 
emqttd

Others:

Ionic 3.10.3
</code></pre>

**Comment by sclausen** [comment]
Thank you very much to be the first to fill out the issue template. I really appreciate this.
Interesting thoughts you've got there. I really doubt it will work, since your app will run even on android/ios in an embedded webkit browser.
I'll give it a shot and try if you're right.

**Comment by jmpmscorp** [comment]
Thanks for your attention, @sclausen.

If I'm honest, I have many doubts too as you pointed about webkit browser. Before submit this "feature", I was searching through Ionic Forums and other webs to know if it would work but I couldn't find anything related. 

I know that mqtt/mqtts from MQTT.js work well with NodeJS. That's why I ask if It could be possible to use with Ionic(?).

Maybe, for now, the only way would be develop with native code...

Thank you again.

**Comment by sclausen** [comment]
Yeah, you're right. Ionic doesn't run nodejs on the phone, just the page in a chromium. And the same restrictions as in all browsers apply, so I'm afraid, there are no direct mqtt connections possible, just via websockets.

Are websockets no option for you?

**Comment by NoWHereRepo** [comment]
@sclausen I have a similar issue: I would like to connect to a local RabbitMQ using Ionic but cannot get it working. RabbitMQ expects to connect to http://127.0.0.1:15675/ws

Any ideas on how to handle this case?

I have no issues with a heroku rabbitmq using this cfg:
export const MQTT_SERVICE_OPTIONS: MqttServiceOptions = {
  connectOnCreate: true,
  hostname: 'm13.cloudmqtt.com',
  username: 'xxxxx',
  password: 'yyyyy',
  port: 36400,
  path: '',
  protocol: 'wss'
};

Thx - also for your great library :)

**Comment by NoWHereRepo** [comment]
I'm sorry. I enabled the wrong plugin in RabbitMQ. In case anyone else has issues:
rabbitmq-plugins enable rabbitmq_web_mqtt

export const MQTT_SERVICE_OPTIONS: MqttServiceOptions = {
  connectOnCreate: true,
  hostname: 'localhost',
  username: 'xxxx',
  password: 'yyyy',
  port: 15675,
  path: '/ws',
  protocol: 'ws'
};
