### ISSUE TITLE
Disable reconnect

### ISSUE THREAD

**Issue by reejinbouk** [sclausen/ngx-mqtt#43]
Hello, how can I disable autoreconnect? I need to leave only manual reconnect.
Thank you!

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ngx-mqtt version: X.Y.Z

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
Just set `reconnectPeriod` to `0` and it will never reconnect automatically.
