### ISSUE TITLE
Warning from ngc, after angular 5 upgrade

### ISSUE THREAD

**Issue by chaymankala** [sclausen/ngx-mqtt#46]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
This warning is being shown on running --prod build
<pre><code>
Warning: Can't resolve all parameters for MqttService in C:/Users/Kiot/Documents/kiot_one/node_modules/ngx-mqtt/src/mqtt.service.d.ts: (?, [object Object]). This will become an error in Angular v6.x
</code></pre>

## Environment

<pre><code>
ngx-mqtt version: 1.16.0

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
I recently also discovered this, but still don't know how to fix it.
I'm on it!

**Comment by chaymankala** [comment]
Thanks! :)

**Comment by sclausen** [comment]
[5.0.0](/sclausen/ngx-mqtt/releases/tag/5.0.0) should fix this problem.
