### ISSUE TITLE
newest Angular 5 AoT compiler throws tapescript error

### ISSUE THREAD

**Issue by aircable** [sclausen/ngx-mqtt#47]
built my app with Ionic 3 and Angular 5

compile with AoT enabled throws error due to changes in the compiler.
Maybe a feature request here since it's based on ng2.
Workaround, compile without AoT.

[20:26:18]  typescript error 
            Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are 
            not supported. Consider replacing the function or lambda with a reference to an exported function, resolving 
            symbol NgModule in 
            /Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/Eidolon/node_modules/angular2-mqtt/node_modules/@angular/core/src/metadata/ng_module.d.ts,
            resolving symbol NgModule in 
            /Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/Eidolon/node_modules/angular2-mqtt/node_modules/@angular/core/src/metadata.d.ts,
            resolving symbol NgModule in 
            /Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/Eidolon/node_modules/angular2-mqtt/node_modules/@angular/core/src/core.d.ts,
            resolving symbol NgModule in 
            /Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/Eidolon/node_modules/angular2-mqtt/node_modules/@angular/core/index.d.ts,
            resolving symbol MqttModule in 
            /Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/Eidolon/node_modules/angular2-mqtt/index.d.ts, 
            resolving symbol MqttModule in 
            /Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/Eidolon/node_modules/angular2-mqtt/index.d.ts

**Comment by sclausen** [comment]
Would you be so kind and post more information? I don't know any line of your code nor the used version of ngx-mqtt.
Ideally post a link to the repository of an example app.

**Comment by aircable** [comment]
Hi,

Thanks for your reply. I build a quick small project with the MQTT library.
It compiles without the --prod option, as a workaround.
But if you use the AOT compiler it crashes. Reason is the upgrade to
Angular 5 and the language change with it.
You see it does not like your included Angular 2 dependency.

Get the project from here: https://github.com/aircable/MQTTtest
run
> ionic cordova resources
first and then
> ionic cordova build ios --prod

......

[12:50:58]  ngc started ...

[12:51:11]  typescript error

            Error encountered resolving symbol values statically. Calling
function 'makeDecorator', function calls are

            not supported. Consider replacing the function or lambda with a
reference to an exported function, resolving

            symbol NgModule in


/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/angular2-mqtt/node_modules/@angular/core/src/metadata/ng_module.d.ts,

            resolving symbol NgModule in


/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/angular2-mqtt/node_modules/@angular/core/src/metadata.d.ts,

            resolving symbol NgModule in


/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/angular2-mqtt/node_modules/@angular/core/src/core.d.ts,

            resolving symbol NgModule in


/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/angular2-mqtt/node_modules/@angular/core/index.d.ts,

            resolving symbol MqttModule in


/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/angular2-mqtt/index.d.ts,


            resolving symbol MqttModule in


/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/angular2-mqtt/index.d.ts



Error: The Angular AoT build failed. See the issues above

    at
/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:233:55

    at step
(/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)

    at Object.next
(/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)

    at fulfilled
(/Volumes/AIRcable/wirelesscables/EclipseProjects/DinnerTime/MQTTtest/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)

    at <anonymous>

On Sat, Nov 18, 2017 at 9:37 PM, Sebastian Clausen <notifications@github.com

**Comment by sclausen** [comment]
Unfortunately, I don't have ios and running `ionic cordova resources` in the cloned project results in the error 
```
[ERROR] Sorry! ionic cordova resources can only be run in an Ionic project directory.
```
I don't know if it's crucial, but I don't see a `ionic.config.json` in your repository.

Nevertheless, I also see you have a very old version of `angular2-mqtt` from march, but you're using angular 5, so I would suggest you try upgrading to `ngx-mqtt@5.0.0`.

**Comment by aircable** [comment]
sorry I forgot to push this file.
It's there now.

**Comment by aircable** [comment]
I tried to upgrade to ngx-mqtt@5.0.0
Now there are even more errors. Are there any dependencies required?
Please checkout the project again, I have updated the dependencies.
BTW you don't need to compile for iOS. You can do browser

ionic cordova build browser --prod

will show you the errors.

Please also check the source, especially the use of your objects. Is that
ok?
file: home.ts and app.module.ts for the service@root.

[11:35:44]  ngc started ...

[11:35:59]  typescript:
node_modules/ngx-mqtt/node_modules/mqtt/types/lib/client-options.d.ts,
line: 96

            Cannot find name 'Buffer'.


      L96:  key?: string | string[] | Buffer | Buffer[] | Object[]

**Comment by sclausen** [comment]
I can't complete signin on running `ionic cordova resources`, since it won't accept my login.
I made a new version, with updated dependencies (@types/node is needed), would you be so kind and try, if it works for you?

**Comment by aircable** [comment]
sure I test, no problem

Ionic account is free, sign up here: https://dashboard.ionicjs.com/apps
Then you only need to do that once, it saves the token.

On Thu, Nov 23, 2017 at 9:39 PM, Sebastian Clausen <notifications@github.com

**Comment by aircable** [comment]
way better. I get this error though. It may be a typings problem. These are
my parameter:

private MQTT_SERVICE_OPTIONS = {
    connectOnCreate: false,
    hostname: 'aircable.net',
    port: 8883, // unsecured web socket port ws:// will not work on
Progressive Web App via https://
    protocol: 'wss',
    path: '',
    username: 'aircable',
    password: 'aircable',
};

And this is the error, which should have worked.

Argument of type '{ connectOnCreate: boolean; hostname: string; port:
number; protocol: string; path:

            string; usern...' is not assignable to parameter of type
'MqttServiceOptions'. Types of property 'protocol'

            are incompatible. Type 'string' is not assignable to type
'"wss" | "ws"'.

**Comment by sclausen** [comment]
I signed up long ago, but didn't completed the process (choosing a plan and so on). Did this before I wrote the last message, but couldn't login then. I tried now again, and et voilà, it works.
I fixed also fixed what was wrong with you code. Some warnings still remain, but the linter tells you what's wrong.

```
ionic cordova build browser --prod                                                                                                                   :(
Running app-scripts build: --prod --platform browser --target cordova
[20:05:40]  build prod started ... 
[20:05:40]  clean started ... 
[20:05:40]  clean finished in 1 ms 
[20:05:40]  copy started ... 
[20:05:40]  deeplinks started ... 
[20:05:40]  deeplinks finished in 43 ms 
[20:05:40]  ngc started ... 
[20:05:44]  ngc finished in 4.32 s 
[20:05:44]  preprocess started ... 
[20:05:44]  preprocess finished in less than 1 ms 
[20:05:44]  webpack started ... 
[20:05:44]  copy finished in 4.52 s 
[20:06:10]  webpack finished in 25.78 s 
[20:06:10]  uglify started ... 
[20:06:10]  sass started ... 
[20:06:11]  sass finished in 914 ms 
[20:06:11]  cleancss started ... 
[20:06:12]  cleancss finished in 1.08 s 
[20:06:26]  uglify finished in 16.56 s 
[20:06:26]  postprocess started ... 
[20:06:26]  postprocess finished in 14 ms 
[20:06:26]  lint started ... 
[20:06:27]  build prod finished in 46.82 s 
> cordova build browser

You have been opted out of telemetry. To change this, run: cordova telemetry on.
[20:06:28]  tslint: src/pages/home/home.ts, line: 65 
            Property 'storage' is declared but never used. 

      L64:  public navCtrl: NavController,
      L65:  private storage: Storage,
      L66:  private backgroundMode: BackgroundMode,

[20:06:28]  tslint: src/pages/home/home.ts, line: 66 
            Property 'backgroundMode' is declared but never used. 

      L65:  private storage: Storage,
      L66:  private backgroundMode: BackgroundMode,
      L67:  private zone: NgZone,

[20:06:28]  tslint: src/pages/home/home.ts, line: 4 
            All imports are unused. 

       L4:  import { Observable } from 'rxjs/Observable';
       L5:  import 'rxjs/add/operator/mergeMap';

[20:06:28]  tslint: src/pages/home/home.ts, line: 23 
            'MqttModule' is declared but never used. 

      L22:  // MQTT
      L23:  import { MqttMessage, MqttModule, MqttService, MqttServiceOptions } from 'ngx-mqtt';

[20:06:28]  tslint: src/components/color-picker/color-picker.ts, line: 98 
            'eventChangeColorDOWN' is declared but never used. 

      L97:  // function for dragging
      L98:  var eventChangeColorDOWN = (event) => {
      L99:      this.updateColorDOWN(event, canvasPalette, this.ctxPalette);

[20:06:28]  tslint: src/app/app.module.ts, line: 11 
            'MqttMessage' is declared but never used. 

      L10:  import { ChartsModule } from 'ng2-charts';
      L11:  import { MqttMessage, MqttModule, MqttService, MqttServiceOptions } from 'ngx-mqtt';

[20:06:28]  lint finished in 1.65 s 

ionic cordova build browser --prod  56,74s user 1,11s system 115% cpu 50,236 total
```

So what I did was upgrading to latest `ngx-mqtt` and add  type to your service options in the app module and your home page like this:
``` typescript
    private MQTT_SERVICE_OPTIONS: MqttServiceOptions = {
        connectOnCreate: false,
        hostname: 'aircable.net',
        port: 8883, // unsecured web socket port ws:// will not work on Progressive Web App via https://
        protocol: 'wss',
        path: '',
        username: 'aircable',
        password: 'aircable',
    };
```

I hope this will now work four you :smile:

**Comment by aircable** [comment]
Of course, works perfectly.
Thank you so much for helping.
Case closed.

**Comment by sclausen** [comment]
Glad I could help.
