### ISSUE TITLE
Demo project build error

### ISSUE THREAD

**Issue by beatrizaldaz** [sclausen/ngx-mqtt#48]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I've tried to test your library with the demo project, and after install dependencies with yarn and npm install, application failed if I run npm run start:
ERROR in ...../ngx-mqtt/demo/node_modules/mqtt/types/lib/types.d.ts (30,14): Cannot find name 'Buffer'.
/ngx-mqtt/demo/node_modules/mqtt/types/lib/types.d.ts (30,14): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/types.d.ts (33,14): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/types.d.ts (44,21): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/types.d.ts (1,1): Cannot find type definition file for 'node'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client-options.d.ts (92,29): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client-options.d.ts (92,38): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client-options.d.ts (96,30): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client-options.d.ts (96,39): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client-options.d.ts (100,28): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client-options.d.ts (100,37): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client.d.ts (40,66): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client.d.ts (102,52): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client.d.ts (104,52): Cannot find name 'Buffer'.ERROR in 
/ngx-mqtt/demo/node_modules/mqtt/types/lib/client.d.ts (1,1): Cannot find type definition file for 'node'.

I've tried to update the ngx-mqtt version to 5.0.0, but the problem is the same.

## Expected behavior

Testing the library with our MQTT broker.

## Environment

<pre><code>
ngx-mqtt version: ^1.16.0

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
Would you be so kind and post your `package.json`?
Do you have installed `@types/node` as a devDependency?

**Comment by beatrizaldaz** [comment]
I didn't do any change in your project. I clone your project and I executed yarn , and npm install.
And when I executed npm run start, the problems appears.

**Comment by beatrizaldaz** [comment]
After updated yarn to last version , the problem was resolved and now I can deploy demo application.
Thanks and sorry for the disturbances.
