### ISSUE TITLE
Simple test with Mosquitto

### ISSUE THREAD

**Issue by nicoparis** [sclausen/ngx-mqtt#49]
Hi,

Thank you for your work.
I was using ngx-mqtt with succesfully (Over Websockets on 8000) with mqtt with this configuration: 

`export const MQTT_SERVICE_OPTIONS = {
  hostname: 'broker.mqttdashboard.com',
  port: 8000,
  path: '/mqtt'
};`

Everything was working fine until this morning (Indeed, broker.mqttdashboard.com service is not responding even on the main website http://www.hivemq.com/demos/websocket-client/)

Having a try with test.mosquitto.org is no working with this conf 

`export const MQTT_SERVICE_OPTIONS = {
  hostname: 'test.mosquitto.org',
  port: 8080,
  path: '/mqtt'
};`

I tried althought another brokerswith no success.

I have   "ngx-mqtt": "^1.14.0", in my package.json 

Have you got an idea what could happen?

Thank you very much

Nicolas

**Comment by sclausen** [comment]
I think you should ask the guys from mqttdashboard.com what happened, since their service is not responding, just as you stated.

Have you tried to install your own mosquitto on your local machine and use the configuration I posted in the readme?

**Comment by nicoparis** [comment]
Thank you for your answer.
Their service is a demo service that's why maybe they don't care too much about maintenance.

Whatever, i basically chose their service because it was the first i manage to make work with ngx-mqtt.
Indeed, trying in the past already but  i didn't manage to use mosquitto test server (test.mosquitto.org) with ngx-mqtt.

That's why i asked you if you have an idea of what can it be, if you have already experience using ngx-mqtt with this test broker (test.mosquitto.org).

I'll have a try locally as you told me.

**Comment by sclausen** [comment]
Sorry, I've never used external brokers like test.mosquitto.org, only brokers on other servers I had control over. I tested with [hummingbird](/lpeterse/haskell-hummingbird) and mosquitto on localhost and remote servers.
The thing with those web services like test.mosquitto.org or broker.mqttdashboard.com is, that they're not reliable and I can't debug on server side, if something goes wrong.
