### ISSUE TITLE
Failing to connect to Apache Active MQ

### ISSUE THREAD

**Issue by lcoetzee** [sclausen/ngx-mqtt#51]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Im trying to connect to an Apache ActiveMQ 5.14.5 broker (this is used in the Eclipse Kapua project).

I am unable to connect and can see the following error in the ActiveMQ log:
o.a.a.b.T.Transport - Transport Connection to: ws://localhost:43182 failed: java.io.IOException

Using the same code I am able to connect to other brokers (e.g. mosquitto).

## Expected behavior

Connect to broker and subscribe/publish  to topics

## Minimal reproduction of the problem with instructions

* Install and run Eclipse kapua docker images (https://www.eclipse.org/kapua/) as described in Getting Started (https://www.eclipse.org/kapua/getting-started.php).

* Configure the ngx-mqtt demo application to connect to the ActiveMQ broker with the following options:
   {hostname: 'localhost',
    port: 61614,
    username: 'kapua-broker',
    password: 'kapua-password'}

* View the docker log:
docker logs image-id

* Error will be visible
o.a.a.b.T.Transport - Transport Connection to: ws://localhost:43182 failed: java.io.IOException

## Environment

<pre><code>
ngx-mqtt version:  "ngx-mqtt": "^5.0.2",

- Broker 
Apache ActiveMQ 5.14.5  with ws transport enabled

Others:

Using the paho client (https://www.eclipse.org/paho/clients/js/) enables the connection
</code></pre>

**Comment by sclausen** [comment]
I'm a little confused, why port `43182` and why `61614`? Unfortunately the getting started doesn't cover the topic "mqtt via websocket". Do you have further information regarding your setup?

**Comment by lcoetzee** [comment]
The documentation on Kapua is very sparse at this time. (Hopefully the project will update them in the near future).

I plan to install just a normal/standalone activemq broker today and test against that (without any of the kapua code which wraps the broker).


**Re: the port**, it isnt documented (or at least I could not find it in the kapua documentation). By scratching around in the code I found the various settings:
In 

> assembly/broker/pom.xml

``   <port>61614</port><!-- MQTT-WS --> ``

and in 
> assembly/broker/src/main/resources/conf/broker/activemq.xml

``  <transportConnector name="ws"
                                uri="ws://0.0.0.0:61614?maximumConnections=1000&amp;wireFormat.maxFrameSize=104857600&amp;transport.publishDollarTopics=true&amp;transport.subscriptionStrategy=mqtt-virtual-topic-subscriptions"/> ``

**Re: my setup**

I did a standard/default kapua install using the docker images (the best I could find in how to run it was in:
[https://www.eclipse.org/kapua/getting-started.php]

It is also possible to build a kapua developer virtualbox image 

[http://krishi-iot.blogspot.co.za/2017/02/krishi-iot-deploy-eclipse-kapua-open.html]

but I havent done this. Might be useful to see more of the log messages from the broker.


In essence for the docker images: 
`` sudo docker run -td --name kapua-sql -p 8181:8181 -p 3306:3306 kapua/kapua-sql:0.3.2 ``

`` sudo docker run -td --name kapua-elasticsearch -p 9200:9200 -p 9300:9300 elasticsearch:5.4.0 -Ecluster.name=kapua-datastore -Ediscovery.type=single-node -Etransport.host=_site_ -Etransport.ping_schedule=-1 -Etransport.tcp.connect_timeout=30s ``

`` sudo docker run -td --name kapua-broker --link kapua-sql:db --link kapua-elasticsearch:es --env commons.db.schema.update=true -p 1883:1883 -p 61614:61614 kapua/kapua-broker:0.3.2 ``

`` sudo docker run -td --name kapua-console --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es --env commons.db.schema.update=true -p 8080:8080 kapua/kapua-console:0.3.2 ``

`` sudo docker run -td --name kapua-api --link kapua-sql:db --link kapua-broker:broker --link kapua-elasticsearch:es --env commons.db.schema.update=true -p 8081:8080 kapua/kapua-api:0.3.2
``
**To test** I used the demo application provided with your package with the settings as in my initial posting above.

I wonder if the issue isnt deeper in the MQTT.js (from what I could see your code wraps around this package)? 

From a **curiosity** viewpoint, how difficult will it be to wrap your code around the PAHO library?

**Comment by sclausen** [comment]
I don't want to wrap my code around PAHO, since I've got bad experience with that library. 

Maybe you could try connecting with mqtt.js alone and post an issue in their repository of it doesn't work. I think this seems to be the wrong place for this issue...

**Comment by lcoetzee** [comment]
I did some testing with different versions of the broker:

The version currently bundled with the version of kapua (0.3.2) is 5.14.5. With that version I cannot connect. However, when using the latest version (currently it is 5.15.2) I am able to connect. It appears as if it was a broker problem all along.

Thank you for the effort.
