### ISSUE TITLE
Angular 5: Getting 'has no exported member ClientPublishOptions' error when compiling

### ISSUE THREAD

**Issue by matthias-herrmann** [sclausen/ngx-mqtt#52]
## I'm submitting a...
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

> ERROR in node_modules/angular2-mqtt/src/mqtt.model.d.ts(2,18): error TS2305: Module '"node_modules/mqtt/types/index"' has no
exported member 'ClientPublishOptions'.
node_modules/angular2-mqtt/src/mqtt.model.d.ts(2,40): error TS2305: Module 'node_modules/mqtt/types/index"' has no exported
member 'ClientOptions'.
node_modules/angular2-mqtt/src/mqtt.model.d.ts(15,38): error TS2312: An interface may only extend a class or another interface.

## Expected behavior
Should compile fine.

## Minimal reproduction of the problem with instructions
New angular 5 application + following documentation README

**Comment by sclausen** [comment]
I see you actually didn't followed the README here on github, but the readme on npmjs.org.
You installed `angular2-mqtt`, which has been renamed 10 month ago to `ngx-mqtt`. Unfortunately, the link to github from npmjs.org redirects to the renamed repository so you have to look careful to notice ;)

Please try again with `npm install --save ngx-mqtt`.

**Comment by matthias-herrmann** [comment]
Oh ok - thanks. I have just been testing some mqtt libraries to figure out which one to use and your library is more an angular style solution which I prefer. You're right I installed the wrong package :)
