### ISSUE TITLE
It's possible to Publish a Uint8Array ?

### ISSUE THREAD

**Issue by gmarab** [sclausen/ngx-mqtt#53]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I'm trying to publish a Uint8Array.
I do not see any errors in the console, but nothing is published.
I looked in the options but I did not find anything about it.
The publication of normal character strings works perfectly.
And on the same broker other types of client publish without problems Uint8Array.
Is it possible to do this kind of publication?
Is there anything I can do ?

Thanks in advance and congratulations for the wonderful work you did.

## Environment

<pre><code>
ngx-mqtt version: 5.0.5

- Broker 
Mosca

Others:

</code></pre>

**Comment by sclausen** [comment]
Yes, this is generally possible. You have too look into the [individual browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) though.
The following snippet would generate all printable ascii characters:
``` typescript
const uint8 = Uint8Array.from({length: 95}, (v, k) => k + 32);
this.mqttService.unsafePublish('test', uint8);
```
In mosquitto, this would look like that
![uint8](https://user-images.githubusercontent.com/916076/35650567-d56251e0-06dc-11e8-9c0c-e5acc9c31a3f.png)

I hope this helps.

**Comment by gmarab** [comment]
Thanks Sebastian,
using unsafePublish works.
Instead using publish does not work.

I would need to work with qos 1 and then be able to check that there are no errors in the publication.
Could you take a look if you can also use the publish method with the Uint8Array?

**Comment by sclausen** [comment]
I don't know whats wrong on your side. The following works also like a charm for me :confused: 
``` typescript
const uint8 = Uint8Array.from({length: 95}, (v, k) => k + 32);
this.mqtt
  .publish('test', uint8, { qos: 1 })
  .subscribe((err) => console.log(err));
```
And you really don't have an error message in your browser?

**Comment by gmarab** [comment]
Yesterday I tried with version 5.2.2 of Angular and it did not work.

I've just updated to 5.2.3 and now it works ...

What version of Angular are you using?

**Comment by sclausen** [comment]
I tested this usecase with 5.2.0.
