### ISSUE TITLE
Custom client ID not stored in MqttService

### ISSUE THREAD

**Issue by marleau** [sclausen/ngx-mqtt#55]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Manually connected to broker with custom client ID.
Asked MqttService for client ID using `this.mqtt.clientID`.
Received default generated ID, not the custom ID.

## Expected behavior

After connecting to broker with custom client ID, receive custom ID from `this.mqtt.clientId`.

**Comment by sclausen** [comment]
Thanks for the report, I'll dig into this.

**Comment by sclausen** [comment]
This bug should be fixed in [5.0.6](/sclausen/ngx-mqtt/releases/tag/5.0.6).
