### ISSUE TITLE
SSL using

### ISSUE THREAD

**Issue by reejinbouk** [sclausen/ngx-mqtt#56]
Hi
How to use it with SSL certificates?
Please provide example?
Thank you

**Comment by sclausen** [comment]
Would you be so kind and elaborate your usecase?
To simply connect via SSL you could also try #20

**Comment by reejinbouk** [comment]
i'm running server with emqtt , and enable using ssl certificates.
i'm successfully testing with MQTT.spy soft usingt CA.cert file

Now I need to connect with ngx-mqtt and CA.crt. How can I use this file or certificate?
Thank you

**Comment by reejinbouk** [comment]
I've found this at MQTT.js:

https://github.com/mqttjs/MQTT.js/blob/master/types/lib/client-options.d.ts

export interface ISecureClientOptions {
  /**
   * optional private keys in PEM format
   */
  key?: string | string[] | Buffer | Buffer[] | Object[]
  /**
   * optional cert chains in PEM format
   */
  cert?: string | string[] | Buffer | Buffer[]
  /**
   * Optionally override the trusted CA certificates in PEM format
   */
  ca?: string | string[] | Buffer | Buffer[]
  rejectUnauthorized?: boolean
}

**Comment by sclausen** [comment]
I also found mqttjs/MQTT.js/issues/741 regarding certificates and wss. The first answer already contains what I suspected, using key, cert, and ca in the browser isn't possible and self signed certificates are the only, yet questionable, option.
I hope this is somehow useful for you.
