### ISSUE TITLE
Connection refused: Not authorized

### ISSUE THREAD

**Issue by mohithkovela** [sclausen/ngx-mqtt#57]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## Current behavior

I want to connect to IBM Watson Iot MQTT but it is not happening. 

this is how my MQTT_SERVICE_OPTIONS look like.

 MQTT_SERVICE_OPTIONS = {
  connectOnCreate: true,
  hostname: 'xxxxxx.messaging.internetofthings.ibmcloud.com',
  port: 8883,
  protocol: "wss",
  clientId: 'd:xxxxxx:yyyyyy:zzzzzzz',
  username: 'API_Key',
  password: 'API_Token'
};
I am using it from Ionic 3 mobile application.
## Expected behavior

I know that I am doing something wrong and this is not an Issue at your side but I just needed help.
## Environment

<pre><code>
ngx-mqtt version: X.Y.Z

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
I'm really sorry, but I have to reject this issue. I have no clue how IBM Watson IoT works, but I don't think this library should cover configuration documentation for IoT platforms who use mqtt under the hood. If you want to know, how to connect please inspect their repository [ibm-watson-iot/iot-java](https://github.com/ibm-watson-iot/iot-java) and see how they use mqtt.
