### ISSUE TITLE
During ng build there is this warning for Angular v6.x

### ISSUE THREAD

**Issue by casper5822** [sclausen/ngx-mqtt#58]
## I'm submitting a warning that will become an error in Angular v6.x...
<pre><code>
[ ] Bug report 
</code></pre>

## Current behavior
With Angular v5.x during ng build there is the following warning:

node_modules/ngx-mqtt/src/mqtt.service.d.ts: (?, [object Object]). This will become an error in Angular v6.x

## Expected behavior
No warning is better.

## Minimal reproduction of the problem with instructions
Just perform a ng build with Angular cli with Angular v5.x

## Environment
angular/cli: 1.6.4
angular-devkit/build-optimizer: 0.0.38
angular-devkit/core: 0.0.25
angular-devkit/schematics: 0.0.48
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.4
schematics/angular: 0.1.13
schematics/schematics: 0.0.13
typescript: 2.4.2
webpack: 3.10.0

ngx-mqtt version: 1.16.0

It's just a reporting issue.

Thank you

**Comment by sclausen** [comment]
ngx-mqtt is rather old. Would you be so kind and try the latest version?

**Comment by sclausen** [comment]
Since this issue just applies to an old version, I'm closing this issue. Please open another one, if you encounter problems with the current version of `ngx-mqtt`

**Comment by casper5822** [comment]
Thank you, it works.
