### ISSUE TITLE
How to unsubscribe from a topic

### ISSUE THREAD

**Issue by avinashs95** [sclausen/ngx-mqtt#59]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

Need to know how to unsubscribe from a topic. There is no specific method mentioned in the documentation. Please help.

**Comment by sclausen** [comment]
Here is an excerpt from the readme. I hope this helps:

> This library exposes a method `observe(filter)`, which returns an Observable. If you subscribe to this observable, the actual mqtt subscription is executed. The topic filter is used to only add matching mqtt messages to the observable. Every other execution of `observe(filter)` with an already used filter will return the same observable. The observable keeps track of the subscribers and executes an mqtt unsubscribe method, if all subscribers have unsubscribed from the observable.

**Comment by avinashs95** [comment]
> The observable keeps track of the subscribers and executes an mqtt unsubscribe method, if all subscribers have unsubscribed from the observable.

I'm still not clear about it. how do we manually unsubscribe a topic using the API?

**Comment by sclausen** [comment]
`MqttService#observe` returns an observable. Observables have (among others) the methods `subscribe` and `unsubscribe`. If you use `MqttService#observe` the first time and then subscribe this observable an actual mqtt subscription is made. The library keeps track of the subscribers of said observable, so if you use observe with the same topic multiple times, there is still just one mqtt-subscription for this topic and the different callbacks receive the same data. So if you use obseve with a already used topic, you will get the same observable. If you then unsubscribe once, no mqtt unsubscribe is made. Only if the last observable subscription is unsubscribed an actual mqtt unsubscribe is called.
I think I will extend the example to clarify this.
