### ISSUE TITLE
protocol: "wss" causes an error 

### ISSUE THREAD

**Issue by dibs** [sclausen/ngx-mqtt#60]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When I use **protocol: 'wss'** in MQTT_SERVICE_OPTIONS I get a compile error:
ERROR in /var/www/ExampleApp/src/app/app.module.ts (31,26): Argument of type '{ hostname: string; port: number; path: string; protocol: string; rejectUnauthorized: boolean; }' is not assignable to parameter of type 'MqttServiceOptions'.
  Types of property 'protocol' are incompatible.
    Type 'string' is not assignable to type '"wss" | "ws"'.

## Expected behavior

site uses wss: as opposed to ws:

## Minimal reproduction of the problem with instructions

Add **protocol: "wss"** to MQTT_SERVICE_OPTIONS.
For MqttService(MQTT_SERVICE_OPTIONS)

## Environment

<pre><code>
ngx-mqtt version: 5.0.7

- Broker 
Mosquitto

Others:

</code></pre>
I'm not very skilled with Angular yet so am not sure if I am missing something but was wondering if this looks like a bug? Thanks for any help

**Comment by sclausen** [comment]
Would you be so kind and post your code? I think you're missing typings here, since this error seems familar to me, but I don't know for sure.
Please post your `app.module.ts`.

**Comment by matzrm** [comment]
Same here. This is my app.module.ts:



`
import {
  MqttModule,
  MqttService
} from 'ngx-mqtt';

export const MQTT_SERVICE_OPTIONS = {
  hostname: 'broker.ovh',
  port: 8884,
  path: '/mqtt',
  username: 'xyz',
  password: 'zyzh',
  protocol: "wss"
};
export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}
`
In method mqttServiceFactory, MQTT_SERVICE_OPTIONS causes the lint error

![image](https://user-images.githubusercontent.com/8723543/37911031-490a6892-310f-11e8-99c7-57ac8dacfaa0.png)

**Comment by sclausen** [comment]
Yeah, as I thought. You need to add the typing `MqttServiceOptions` to `MQTT_SERVICE_OPTIONS`.
Did this helped?

**Comment by matzrm** [comment]
Yes, 

this solve the issue! Thank you!

**Comment by sclausen** [comment]
Done

**Comment by dibs** [comment]
This was my issue too. I change to match your code and imported the MqttServiceOptions from ngx-mqtt and not all is working!

Thank you both!

**Comment by biapar** [comment]
Is there not TCP protocol?

**Comment by sclausen** [comment]
@biapar No, this won't work, since you're using mqtt via websockets in the browser.

**Comment by bestbelief** [comment]
Excuse me, how do I add TLS certificates in it?Is it in MqttServiceOptions?

**Comment by matzrm** [comment]
In my opinion is better use a certificate yet signed for browser, like these emitted by lets encrypt. In this way you dont Need to add It.

**Comment by bestbelief** [comment]
@matzrm Thank you for your reply,  But the application server and the message server have different addresses.  Can this situation work normally?

**Comment by sclausen** [comment]
As I said four months ago, you can't use those certificates in the browser via websockets.

**Comment by bestbelief** [comment]
Ok, It seems that I can only think of other ways.thank you very much!

**Comment by dibs** [comment]
@sclausen I am using WSS to an address that has a let's encrypt certificate.
Does what you indicate mean it is not encrypted?

**Comment by bestbelief** [comment]
@dibs Hello,i want to know where is your encryption certificate located?

**Comment by sclausen** [comment]
Maybe #20 helps regarding this issue.

There is a difference between using wss and authenticating via client certificates. If your endpoint has a certificate it works well. But you can't authorize with client certificates via websocket.

**Comment by bestbelief** [comment]
Ok, I will try !  Thank you for your help.
