### ISSUE TITLE
[MqttClientSessionsManager] [Error]: The first packet from a client must be a 'CONNECT' packet [MQTT-3.1.0-1]. MQTTnet.Exceptions.MqttProtocolViolationException: The first packet from a client must be a 'CONNECT' packet [MQTT-3.1.0-1].

### ISSUE THREAD

**Issue by biapar** [sclausen/ngx-mqtt#65]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
[MqttClientSessionsManager] [Error]: The first packet from a client must be a 'CONNECT' packet [MQTT-3.1.0-1].
MQTTnet.Exceptions.MqttProtocolViolationException: The first packet from a client must be a 'CONNECT' packet [MQTT-3.1.0-1].

## Expected behavior

Connected

## Environment

<pre><code>
ngx-mqtt version: 5.0.8

- Broker : MQTTnet

Others:

</code></pre>

**Comment by sclausen** [comment]
It seems you're using a broker that doesn't implemented the mqtt protocoll correctly.
I'm really sorry, but I can't help you with this.

**Comment by biapar** [comment]
No. The problem is that the broker by default use TCP. I'm setting up with ws and it works now.

**Comment by hugorojas1121** [comment]
Hello @biapar! How did you solve the problem? I'm trying deploying on Nginx witn MQTTnet and this is the same problem, any solutions?  Thank you in advance!
