### ISSUE TITLE
Is't possible to pass binary data into payload?

### ISSUE THREAD

**Issue by biapar** [sclausen/ngx-mqtt#67]
Is't possible to pass binary data into payload?

**Comment by sclausen** [comment]
Please see #53. Does it help?

**Comment by biapar** [comment]
Maybe. I'll try and with to send an image into payload.

**Comment by sclausen** [comment]
Okay, since mqtt is a binary protocol and you're able to have binary data in the browser (e.g.how to publish an `Uint8Array` described in #53), you can publish binary data as a payload so this issue is closed.
If you have any further questions, feel free to ask.
