### ISSUE TITLE
Unable to disconnect from MQTT

### ISSUE THREAD

**Issue by gioid** [sclausen/ngx-mqtt#68]
- [X] **I have searched for similar issues in this repository, but couldn't find one.**
## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior
If you disconnect the client, for example in the onError callback, the reconnection policy still works and you still receive messages. For example https://jsfiddle.net/5nwwot6t/1/

## Expected behavior
I expected that after the disconnect() the reconnection policy will be ignored.

## Minimal reproduction of the problem with instructions
https://jsfiddle.net/5nwwot6t/1/

## What is the motivation / use case for changing the behavior?
If you want to close the MQTT connection after a bad login or to save energy.

## Environment

<pre><code>
ngx-mqtt version: 5.0.8

- Broker: VerneMQ.

</code></pre>

**Comment by sclausen** [comment]
Your reproduction is plain mqtt.js code, not ngx-mqtt. if you have this bug with plain mqtt.js, you should file an issue in their repository. Or isn't this what you actually tried with ngx-mqtt?

**Comment by sclausen** [comment]
Besides this, you mixed `mqtt.js` code and `ngx-mqtt` code. `mqtt.js` has no method `disconnect`. There it's called `end`.

**Comment by sclausen** [comment]
Please have a look at my attempt to reproduce your bug and tell me, if I did something different than you: [ngx-mqtt-issue68](https://ngx-mqtt-issue68.stackblitz.io/). I can't reproduce the behavior you described.

**Comment by gioid** [comment]
Sorry for the delay, I was unable to look at your example so I took a few days to reply. 
I was wrong with the "repro-fiddle", I dit not realize that I was using plain mqtt: so that jsfiddle is quite unuseful right now :-).

I checked your sources and compared to mine: I understand that the difference is in the way the MQTT connection is required. In my code I call the `connect()` method after the MqttService constructor and this seems to create another client that overwrites the client created in the constructor:

`let mqttSvc = new MqttService(MQTT_OPTIONS);`
`mqttSvc.connect();`

If you change the code of your example and you add a `connect()` on the `mqtt` object, you should lose the control of the underlying MQTT client, regardless of `mqtt.disconnect()` attempts.

I checked the source of the `connect()` method in the mqtt.service.ts and it seems that the method override the `this.client` regardless of its state:

`        if (!client) {`
`            this.client = MQTT.connect(this._url, mergedOptions);`
`        }`
`        else {`
`            this.client = client;`
`        }`

Am I right? 

For the moment I removed the `connect()` method in my source and it works as expected, so maybe it is not a so important issue.

**Comment by sclausen** [comment]
Thanks for your help. I changed the code to close the old client, if you have an existing one and execute `connect` without providing a client. [5.2.0](https://github.com/sclausen/ngx-mqtt/releases/tag/5.2.0) should now work in the case you explained.
If I did something wrong, please feel free to open another issue.
