### ISSUE TITLE
Catch Error Connection

### ISSUE THREAD

**Issue by matzrm** [sclausen/ngx-mqtt#70]
- [ x] **I have searched for similar issues in this repository, but couldn't find one. I read a similar question, but it speaks about how to handle failed authentication with Mosquitto broker. I think that is not the same problem. **
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

I can't catch connection error subscribing on onError.

## Expected behavior

Handles connection error to show message to user.

## Minimal reproduction of the problem with instructions
1 - Stop the broker service 
2 - Open client and waiting for message from onError Observer.
3 - No events fired by Observer  I can only read a message in the console printed by stream.js. 

PS;
Generally with ngx-mqtt I can't catch neither error message. I have to subscribe onState to retry connection status. 

## Environment

<pre><code>
ngx-mqtt version: 5.0.7

- Broker 
Mosquitto version 1.4.8

Others:

</code></pre>

**Comment by sclausen** [comment]
Thanks for the issue. [5.1.0](https://github.com/sclausen/ngx-mqtt/releases/tag/5.1.0) should fix the bug. If you have further issues, feel free to file another one.

**Comment by matzrm** [comment]
Thank you for fix it.
