### ISSUE TITLE
doesn't work npm install ngx-mqtt --save

### ISSUE THREAD

**Issue by cedricve** [sclausen/ngx-mqtt#72]
When I try to install this library I'm getting errors.

[..................] / normalizeTree: sill install loadCurrentTree
npm ERR! addLocal Could not install /var/www/2017/kerberos-cloud-ng/kerberos.ng/node_modules/ngx-mqtt/mqtt.js
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v6.5.0/bin/node" "/home/vagrant/.nvm/versions/node/v6.5.0/bin/npm" "install" "ngx-mqtt" "--save"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path /var/www/2017/kerberos-cloud-ng/kerberos.ng/node_modules/ngx-mqtt/mqtt.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/www/2017/kerberos-cloud-ng/kerberos.ng/node_modules/ngx-mqtt/mqtt.js'
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/2017/kerberos-cloud-ng/kerberos.ng/node_modules/ngx-mqtt/mqtt.js'
npm ERR! enoent This is most likely not a problem with npm itself

**Comment by sclausen** [comment]
Sorry, I didn't flagged the alpha as next. Now it should work again. Thanks for this issue!
