### ISSUE TITLE
username & password

### ISSUE THREAD

**Issue by cedricve** [sclausen/ngx-mqtt#73]
Hey @sclausen , is it possible to set username and password?

**Comment by sclausen** [comment]
Yes, just use the fields in the `IMqttServiceOptions`.

**Comment by cedricve** [comment]
@sclausen just wondering what the attributes are, as it's not in the interface?
https://github.com/sclausen/ngx-mqtt/blob/master/src/mqtt.model.ts#L10-L21

**Comment by sclausen** [comment]
You have to go into the interface which is extended. And sometimes, if needed, you have to go deeper into the extension chain. Does your ide have a shortcut to show the definition of something?
