### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: connectable.connect is not a function

### ISSUE THREAD

**Issue by cedricve** [sclausen/ngx-mqtt#75]
Hey @sclausen,

Got it working without username/password but getting an connect error when trying to subscribe to a topic. I'm using Angular 5.1

    this.subscription = this._mqttService.observe('my/topic').subscribe((message) => {
        this.message = message.payload.toString();
    });

**Comment by sclausen** [comment]
Please provide a proper reproduction. Just this small snippet doesn't help understanding why your app isn't connecting.

**Comment by cedricve** [comment]
I've setup a mosquitto mqtt server with docker. However I see it tries to connect, but the server throws errors.

1524050472: New client connected from 172.17.0.1 as client-lfh6sbkjlsk (c1, k10).
1524050635: Socket error on client client-lfh6sbkjlsk, disconnecting.

**Comment by cedricve** [comment]
looks like the connectable object is an observerable and doesn't has a connect() function.

![error](https://user-images.githubusercontent.com/1546779/38934239-9070eec2-431b-11e8-8ee2-56679428e391.PNG)

**Comment by sclausen** [comment]
I really need code. No package json, no msquitto.conf, no further setup, just a stacktrace really doesn't help.

**Comment by cedricve** [comment]
Sure, I'll provide you some logs. However I confirm the unsafePublish is working properly.

**Comment by cedricve** [comment]
My package.json

      "dependencies": {
        "@angular/animations": "^5.2.10",
        "@angular/cdk": "^5.2.5",
        "@angular/common": "^5.2.10",
        "@angular/compiler": "^5.2.10",
        "@angular/core": "^5.2.10",
        "@angular/forms": "^5.2.10",
        "@angular/http": "^5.2.10",
        "@angular/material": "^5.2.5",
        "@angular/platform-browser": "^5.2.10",
        "@angular/platform-browser-dynamic": "^5.2.10",
        "@angular/router": "^5.2.10",
        "@fortawesome/fontawesome": "^1.1.5",
        "@ngrx/db": "^2.0.2",
        "@ngrx/effects": "^4.0.0",
        "@ngrx/router-store": "^4.0.4",
        "@ngrx/store": "^4.0.0",
        "@ngrx/store-devtools": "^4.0.0",
        "@sentry/webpack-plugin": "^1.5.1",
        "@swimlane/ngx-charts": "^7.3.0",
        "@types/jquery": "^3.3.1",
        "@types/lodash": "^4.14.107",
        "@types/mixpanel": "^2.11.1",
        "angular2-notifications": "^0.9.9",
        "angularfire2": "^5.0.0-rc.5-next",
        "bootstrap": "^4.1.0",
        "core-js": "^2.5.5",
        "d3": "^4.12.0",
        "firebase": "^4.12.1",
        "font-awesome": "^4.7.0",
        "hammerjs": "^2.0.8",
        "jquery": "^3.2.1",
        "lodash": "^4.17.4",
        "mixpanel-browser": "^2.20.0",
        "ng-push": "^0.2.1",
        "ng2-date-picker": "^2.9.0",
        "ng2-ion-range-slider": "^1.0.3",
        "ng2-timezone-selector": "^0.2.4",
        "ng2-toastr": "^4.1.2",
        "ng4-geoautocomplete": "^0.1.0",
        "ngrx": "^2.0.1",
        "ngx-bar-rating": "^1.1.0",
        "ngx-clipboard": "^10.0.0",
        "ngx-mqtt": "^5.3.0",
        "ngx-stripe": "^0.2.3",
        "ngx-toastr": "^8.4.0",
        "ngx-zendesk-webwidget": "^0.1.3",
        "plotly.js": "^1.36.0",
        "popper.js": "^1.14.3",
        "pusher-angular": "^1.0.0",
        "raven-js": "^3.24.2",
        "rxjs": "5.4.3",
        "ts-md5": "^1.2.4",
        "zone.js": "^0.8.26"
      },

Mosquito.conf

    # Place your local configuration in /mqtt/config/conf.d/

    pid_file /var/run/mosquitto.pid

    persistence true
    persistence_location /mqtt/data/

    user mosquitto

    # Port to use for the default listener.
    port 1883


    log_dest file /mqtt/log/mosquitto.log
    log_dest stdout
    listener 9001
    protocol websockets

**Comment by sclausen** [comment]
Thanks for the config files. Code is still pending...

**Comment by cedricve** [comment]
@sclausen if it might help, I'm using this docker containers.

    docker run -ti -p 1883:1883 -p 9001:9001 toke/mosquitto

**Comment by JaviBecerra** [comment]
@cedricve I started using ngx-mqtt today and was having the same error with 'connectable.connect', with ngx-mqtt version 5.3.0. 
Installing version ngx-mqtt version 5.2.0 (npm install ngx-mqtt@5.2.0 --save) instead works fine for me.

**Comment by sclausen** [comment]
Does [5.4.0](https://github.com/sclausen/ngx-mqtt/releases/tag/5.4.0) fix your error?

**Comment by cedricve** [comment]
trying out right now @sclausen thanks!

**Comment by cedricve** [comment]
thanks fixed! @sclausen

**Comment by paulinhofoz** [comment]
Hello.
was looking at the example  ngx-mqtt: 
export const MQTT_SERVICE_OPTIONS = {
  hostname: '13 .127.53.13 ',
  port: 9001,
  path: '/ mqtt'
};

(https://github.com/sclausen/ngx-mqtt)

and in the "path" section, I do not know what I mean, because when I use MyMQTT and MQTT Dash mobile applications, the path is not requested, but the host (IP) and topic.
Error message: ERR_CONNECTION_RESET and ERR_CONNECTION_REFUSED according to what I put in this path.
Can you help me?
