### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by chrste90** [sclausen/ngx-mqtt#82]
The master is currently broken. The files `mqtt-types.ts` and `/vendor/mqtt.browserified.js` don't exist but are referenced in `mqtt.service.ts` and `mqtt.model.ts`.

**Comment by chrste90** [comment]
I think the mqtt-types is still Missing. At least in the commit which closed the issue.

**Comment by sclausen** [comment]
I don't know what you're talking about :grimacing:
