### ISSUE TITLE
I'm getting error Argument of type '{ provide: typeof MqttService; useFactory: () => MqttService; }' is not assignable to parameter of type 'IMqttServiceOptions'.

### ISSUE THREAD

**Issue by sainipradeep** [sclausen/ngx-mqtt#83]
Hello i'm using angular 4. Getting this error  <img width="1396" alt="screen shot 2018-05-07 at 1 47 00 pm" src="https://user-images.githubusercontent.com/9319048/39692112-8588734a-51fd-11e8-8336-64f513a224d0.png">

**Comment by chrste90** [comment]
It looks like you're using v6 of ngx-mqtt. The syntax has changed there and i created a PR to change the README: https://github.com/sclausen/ngx-mqtt/pull/84

Also i'm not sure if v6 will work with angular 4 because it now uses rxjs v6. You may need to use an older version with angular 4.

**Comment by sclausen** [comment]
It shouldn't work with angular <= 6.0.0. Some techniques, like the tree-shakeable service aren't implemented there.

**Comment by sclausen** [comment]
Oh I forgot: No Issue Template, no service!
