### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.defineInjectable is not a function

### ISSUE THREAD

**Issue by chaymankala** [sclausen/ngx-mqtt#88]
- [x ] **I have searched for similar issues in this repository, but couldn't find one.**
- [x ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [x ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report  
- [ ] Feature request

## Current behavior
TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.defineInjectable is not a function
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0__angular_core__.defineInjectable is not a function
    at mqtt.service.js:419
    at Object.<anonymous> (mqtt.service.js:421)
    at __webpack_require__ (bootstrap fa7e388759ae2ea5a0f0:54)
    at Object.module.exports (vendor.js:97853)
    at __webpack_require__ (bootstrap fa7e388759ae2ea5a0f0:54)
    at Object.exports.isArray (vendor.js:56358)
    at __webpack_require__ (bootstrap fa7e388759ae2ea5a0f0:54)
    at Object.794 (SqliteService.ts:8)
    at __webpack_require__ (bootstrap fa7e388759ae2ea5a0f0:54)
    at Object.430 (main.ts:9)

I'm seeing this fatal error if I upgrade above v5.0.6 

## Minimal reproduction of the problem with instructions
Import ngx-mqtt into injectable.

## Environment

<pre><code>
ngx-mqtt version: 6.1.2

- Broker Mosquitto

Others:
No
</code></pre>

**Comment by sclausen** [comment]
Would you be so kind and add a proper reproduction? Without any code I can't analyze this. A GitHub repository or stackblitz would be great.

**Comment by chaymankala** [comment]
Im sorry, My bad...I did not upgrad my angular version to 6+ and I updated ngx-mqtt to 6+. After updating to angular 6.0.2, ngx-mqtt@latest is working fine.

Thanks for responding,
I'm closing this issue 👍

**Comment by esthonwood** [comment]
Hi @sclausen. I'm new to Ionic 3 and I am having the same error right now in my app.module.ts. I'm not sure if I need to use a lower version of this plugin. Please help me out, I can't find any detailed tutorial for this plugin. I would greatly appreciate your help. Thank you in advance.

Here's my Ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.2.1 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.9.2
   NodeJS            : v6.9.2 
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255

```

package.json

```
{
  "name": "app",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.15.0",
    "@ionic-native/splash-screen": "~4.15.0",
    "@ionic-native/status-bar": "~4.15.0",
    "@ionic/storage": "^2.2.0",
    "cordova-sqlite-storage": "2.5.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "mqtt": "^2.18.8",
    "ngx-mqtt": "6.7.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {}
    }
  }
}

```

app.module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { IonicStorageModule } from '@ionic/storage';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
// import { ListPage } from '../pages/list/list';
import { LoginPage } from '../pages/login/login';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

// MQTT
import { Observable } from 'rxjs/Observable';
import {
  // IMqttMessage,
  MqttModule,
  MqttService,
  IMqttServiceOptions
} from 'ngx-mqtt';

export const MQTT_SERVICE_OPTIONS: IMqttServiceOptions = {
  hostname: 'wss://iot.eclipse.org',
  port: 443,
  path: '/ws'
};

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    // ListPage,
    LoginPage
  ],
  imports: [
    BrowserModule,
    MqttModule.forRoot({
      hostname: 'wss://iot.eclipse.org',
      port: 443,
      path: '/ws'
    }),
    IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot(),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    // ListPage,
    LoginPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    // MqttService,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

```
