### ISSUE TITLE
"export 'inject' (imported as 'i0') was not found in '@angular/core'

### ISSUE THREAD

**Issue by utkarshns** [sclausen/ngx-mqtt#89]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request

## Current behavior
While trying to implement ngx-mqtt in a new Angular 5 project, I get the following error:
```
./node_modules/ngx-mqtt/src/mqtt.service.js
419:124-133 "export 'inject' (imported as 'i0') was not found in '@angular/core'
@ ./node_modules/ngx-mqtt/src/mqtt.service.js
@ ./node_modules/ngx-mqtt/src/mqtt.module.js
@ ./node_modules/ngx-mqtt/src/index.js
@ ./src/app/modules/device-types/pump-control/pump-control.component.ts
@ ./src/app/modules/device-types/pump-control/pump-control.module.ts
@ ./src/$$_lazy_route_resource lazy
@ ./node_modules/@angular/core/esm5/core.js
@ ./src/main.ts
@ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

## Minimal reproduction of the problem with instructions
A new angular project and implementation of ngx-mqtt

## Environment

<pre><code>
ngx-mqtt version: 6.1.2

- Broker: Mosquitto

**Comment by sclausen** [comment]
Sorry you can't use ngx-mqtt>=6 in an angular 5 project. Please use the versions before.
