### ISSUE TITLE
Multiple subscriptions to the topic with retained message

### ISSUE THREAD

**Issue by stepanmracek** [sclausen/ngx-mqtt#92]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**

## I'm submitting a...
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Current behavior
When I have multiple subscriptions to the topic having retained message, only first few subscriptions get the message. This used to work in ngx-mqtt@5.2. I am unable to check whether it is working in 5.3 since I got an error when running the web (see below if it is relevant). In 5.4 and 6.1.2 it's not working.

## Expected behavior
I expect that all subscriptions receives the retained message.

## Minimal reproduction of the problem with instructions
I have Mosquitto broker running on ports 1883 (MQTT) and 1884 (Websockets). I published the retained message using command `mosquitto_pub -t "topic" -m "message" -r`

I have a minimal working example here. It's just simple page with "Observe" button that subscribes to the "topic" and when message comes, it is added to the list below button. When the component is loaded, it subscribes 10 times to the "topic" with small delays between individual subscriptions. If you unsubsribe all subscriptions and subscribe again it works for first new subscription but not for the later.
 
[Repository for Angular5 using ngx-mqtt@5.4](https://github.com/stepanmracek/ngx-mqtt-test-ng5)
[Repository for Angular6 using ngx-mqtt@6.1.2](https://github.com/stepanmracek/ngx-mqtt-test-ng6) (edit: fix link)

If you downgrade ngx-mqtt to 5.2 in ngx-mqtt-test-ng5 then everything is working fine.

## What is the motivation / use case for changing the behavior?
I have a web application that control embedded device running MQTT broker. In some parts of my application I need to subscribe to the same topics that are also subscribed somewhere else.

## Environment
<pre><code>ngx-mqtt version: both 5.4.0 and 6.1.2
- Broker Mosquitto</code></pre>

## Additional info
When I was trying to check if 5.3 is affected, the following error raised in browser console:
<pre><code>AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: connectable.connect is not a function
    at RefCountOperator.call (refCount.js:25)
    at Observable.subscribe (Observable.js:157)
    at MapOperator.call (map.js:57)
    at Observable.subscribe (Observable.js:157)
    at MapOperator.call (map.js:57)
    at Observable.subscribe (Observable.js:157)
    at AppComponent.observe (app.component.ts:44)
    at AppComponent.ngOnInit (app.component.ts:27)
    at checkAndUpdateDirectiveInline (core.js:12411)
    at checkAndUpdateNodeInline (core.js:13935)</pre></code>

**Comment by sclausen** [comment]
Thank you very much for the comprehensive bug report. I'll see to it.

**Comment by sclausen** [comment]
Status Report: I think I broke the behavior with the fix for #69. I'll check how I can fix this error without introducing a new regression.

**Comment by sclausen** [comment]
[6.2.0](https://github.com/sclausen/ngx-mqtt/releases/tag/6.2.0) should fix this issue. Can you confirm?

**Comment by stepanmracek** [comment]
Hi, thanks for the quick fix. You are doing a great work. I just checked and it solved my original problem. I went through #69 as well as this fix and there is possibly another bug. I will post another issue here if it is needed.

You can reproduce it when you have MQTT broker with no messages and you replace `ngOnInit() {...}` content in my project with the following code:
```typescript
this.observe();
setTimeout(() => this.mqtt.unsafePublish('topic', 'unretained message', { retain: false, qos: 0 }), 2000);
setTimeout(() => this.observe(), 4000);
setTimeout(() => this.mqtt.unsafePublish('topic', 'retained message', { retain: true, qos: 0 }), 6000);

// these observes will not receive retained message...
setTimeout(() => this.observe(), 8000);
setTimeout(() => this.observe(), 10000);

// ...until all observations are cleared
setTimeout(() => {
    this.mqttSubscriptions.map(s => s.subscription).filter(s => !!s).map(s => s.unsubscribe())
    this.mqttSubscriptions = [];
}, 12000);

// Now it will receive the retained message.
setTimeout(() => this.observe(), 14000);
setTimeout(() => this.observe(), 16000);
```

Once you refresh the page, everything will work and the bug is no longer reproducible until you restart MQTT. I think that this bug occures only when the first message after subscribe is non-retained.

**Comment by sclausen** [comment]
Thank you very much for the proper reproduction!
As you assumed, I would appreciate, if you could open a new issue for this. I will post everything I discovered in the meantime there.
