### ISSUE TITLE
[Feature request] set number of replayed messages in observeRetained()

### ISSUE THREAD

**Issue by stepanmracek** [sclausen/ngx-mqtt#96]
- [x] **I have searched for similar issues in this repository, but couldn't find one.**
- [x] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request

## Current behavior
Hello,
The new method `observeRetained()` replays all messages that have been published between the first subscription of the topic and current call of `observeRetained()`. 

Could you please add an optional parameter that will specify, how many messages should be buffered? In order to do not break backward compatibility, the method signature might be like:

```typescript
observeRetained(filterString: string, bufferSize: number = Number.MAX_VALUE): Observable<IMqttMessage>;
```

If I understand your code correctly, the `bufferSize` parameter can be directly passed to the `publishReplay()` function that is a parameter to private `_generalObserve()` method.

## What is the motivation / use case for changing the behavior?
In many cases, subscriber is not intrested in the past but only in the last values (if it is any)

**Comment by sclausen** [comment]
Oh, it seems I forgot to set the parameter of publishReplay to 1. I intended to just replay the latest message to mimic the retained message behavior. Do you really need to configure a different value than a bufferSize of 1?

**Comment by stepanmracek** [comment]
No, I just need 1. I thought that the omitting of bufferSize is intentional.

**Comment by sclausen** [comment]
Great, then I've got a [new release](https://github.com/sclausen/ngx-mqtt/releases/tag/6.3.1) for you :smile: 
Anyway, many thanks for the PR and your contribution.
