### ISSUE TITLE
Cannot integrate with Ionic3

### ISSUE THREAD

**Issue by praseedm** [sclausen/ngx-mqtt#98]
- [ x] **I have searched for similar issues in this repository, but couldn't find one.**
- [ ] **I have read the README and have a basic understanding how angular works.**
## I'm submitting a...

- [x ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Feature request

## Current behavior

subscription to topic not updating data.

## Minimal reproduction of the problem with instructions

Using ionic 3 with ngx-mqtt@5.4.0 , subscription to topic is not working. Please help me to integrate mqtt with ionic . 
Is ngx-mqtt version or angular versions iam using causing this error?.

ionic info

cli packages: (/home/web/.nvm/versions/node/v8.11.2/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.2
    npm               : 5.6.0
    OS                : Linux 4.4

Environment Variables:

    ANDROID_HOME : /home/web/Android/Sdk

Misc:

    backend : pro

## Environment

- Broker 
cloudmqtt.com.

Others:

when i use ngx-mqtt latest version it throws built error.
![ngx_error](https://user-images.githubusercontent.com/13822610/41902975-567b8912-7952-11e8-833e-ee3d1c5f0ddc.png)

using ngx-mqtt@5.4.0
- app.module.ts -
``` typescript
import { MqttModule, MqttService , IMqttServiceOptions} from 'ngx-mqtt';

export const MQTT_SERVICE_OPTIONS = {
  hostname: 'm10.cloudmqtt.com',
  port: 34256,
  rotocol: 'ws',
  path: '/'
};

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],

  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    })
  ],
```
- home.ts - 
``` typescript
import {MqttService, IMqttMessage} from 'ngx-mqtt';
import { Observable, Subscription } from 'rxjs'

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage implements OnDestroy {
  message : string = "def";
  private subs : Subscription;

  constructor(public navCtrl: NavController,
    private mqttService: MqttService) {

    this.subs = this.mqttService.observe('first').subscribe(
      (message : IMqttMessage) => {
        console.log(message);
        this.message = message.payload.toString();
      }
    );

  }

  public ngOnDestroy() {
    this.subs.unsubscribe();
  }

}
```
Please help me to integrate ngx-mqtt with ionic.

[EDIT BY @sclausen] In the future, please properly format your issue.

**Comment by sclausen** [comment]
Would you be so kind and post the angular version you're using?

**Comment by praseedm** [comment]
Thank you for your time,

git repo to code : https://github.com/praseedm/Mqtt_test

how can i contact you ? , can you please provide me your email address.

**Comment by praseedm** [comment]
Iam using cloudmqtt.com as mqtt broker.

**Comment by sclausen** [comment]
That's irrelevant for the build error. Thanks for the repository, I'll dig into it.

**Comment by sclausen** [comment]
I'm really sorry, but I can't reproduce your behaviour. Except for a linting warning, the app builds fine and is served without any error. Did you try to clean your `node_modules` folder?

**Comment by praseedm** [comment]
please use my new push.
git repo to code : https://github.com/praseedm/Mqtt_test
which ngx-mqtt version should i use with angular/core: "5.2.11" ?.
how can i contact you ? , can you please provide me your email address.

**Comment by sclausen** [comment]
My email is github@sebastian-clausen.de.

**Comment by sclausen** [comment]
You should've received my email address via mail from github.

Your last push just included the linter fix, so this doesn't result in this build error either.
ngx-mqtt@5.4.0 also is the version of choice.

I encountered this error before and it had something todo with mixing angular 6 code with angular 5 code, since `defineInjectable` is new in `angular@6`. You're really sure, ngx-mqtt is 5.4.0 and you're using angular 5? Did you tried to delete the whole `node_modules` folder and reinstall?

**Comment by praseedm** [comment]
ngx-mqtt@5.4.0 working well . Issue resolved.
Thank you

**Comment by sclausen** [comment]
So you actually didn't used `ngx-mqtt@5.4.0` in the first place, as stated?
