### ISSUE TITLE
Invalid credentials do not trigger error events.

### ISSUE THREAD

**Issue by yanosz** [sclausen/ngx-mqtt#99]
Playing around with ngx-mqtt, I noticed that connection errors due to invalid credentials are getting lost: Code:
```typescript
@Injectable({
  providedIn: 'root',
})
export class MqttAdapterService {

  message: String;

  constructor(private _mqttService: MqttService) {

  }

  subscribe(username: string, password: string) {
    MQTT_SERVICE_OPTIONS.username = username;
    MQTT_SERVICE_OPTIONS.password = password;

    // 1st try - should fail "Error: mqtt client not connected
    try {
      this._mqttService.observe('/');
    } catch (err) {
      console.log(err); // this is triggered
    }

    // What happens here?
    this._mqttService.connect(MQTT_SERVICE_OPTIONS);

    // This should fail somehow, if username / password are wrong.
    try {
      this._mqttService.observe('/').subscribe((m) => {
        console.log('A message');
        }, (e) => {
        console.log('An error');
      });
    } catch (err) {
      console.log('Ooops');
      console.log(err);
    }
  }
}
```

## Current behavior
* The 1st observer call fails with "Error: mqtt client not connected" (Exception is raised)
* If credentials are valid, the subscription is successful
* If credentials are invalid, no error is shown

## Expected behavior
* If credentials are invalid, an error is shown -  either synchronous (exception) or asynchronous using the observable

## Environment

<pre><code>
ngx-mqtt version: 6.3.1

- Broker Mosquitto, etc.
</code></pre>

**Comment by yanosz** [comment]
Hello,

thanks for your answer - I don't get any error.

Greetz, yanosz

**Comment by sclausen** [comment]
Do you get an error if you try [plain mqtt.js in the browser](https://sclausen.github.io/ngx-mqtt/#important-note)?

**Comment by yanosz** [comment]
thanks for your feedback.

> Do you get an error if you try plain mqtt.js in the browser?

Well .. that's hard. Take this code for example:

```html
<html>
<head>
  <title>test ws mqtt.js</title>
</head>
<body>
<script src="/assets/mqtt.browserified.js" ></script>
<script type="text/javascript">
  console.log("Start..");
  var client = mqtt.connect('wss://mqtt.jluehr.de:1885', {username: 'esp32-dev-1', password: 'secret'});

  client.subscribe("mqtt/demo");

  client.on("connect", function() {
    console.log("Connected");
  });

  client.on("close", function() {
    console.log("Closed");
  });

  client.on("message", function (topic, payload) {
    alert([topic, payload].join(": "));
    client.end();
  })


  client.publish("mqtt/demo", "hello world!");
</script>
</body>
</html>
```

- If I don't provide any username / password (i.e. commenting out the options), the console logs "**Closed**"
- If I provide a valid username / password, the console logs "**Connected**" (`secret` is not valid ;-).

From my understanding, mqtt-ngx doesn't handle the closed event - or - I don't get docs on doing so.

Greetz, yanosz

**Comment by sclausen** [comment]
I think I found out what's wrong. Your `ngx-mqtt` demo has a little flaw. In the module, you used the default `MQTT_SERVICE_OPTIONS`, which will let the service automatically try to connect. Since you don't pass the credentials there but in the controller, it will result in a rejection you can't catch, because you haven't subscribed to the onError or onConnect observable yet. You just get the closed event later. If you want to only connect in the controller, you have to build your own options with the field `connectOnCreate` to `false`. So if you try with wrong credentials this caused your close event being fired twice.

**Comment by yanosz** [comment]
Thanks for your feedback. 

I don't think, that connectOnCreate changes sth - of course, you're right, I missed that when compiling a minimal example.

The full code is at: https://github.com/FieldTracks/fieldmon/blob/master/src/app/mqtt-adapter.service.ts - unfortunatly, its somewhat messy atm, cause I'm still making my way through Angular 6 (... tried AngularJS years ago ...). The system is deployed at: https://mqtt.jluehr.de .. but I'think that' you're better of testing it locally.

**Comment by sclausen** [comment]
I really can't reproduce where the closed event could be swallowed, since everything works finde for me.
I can't reproduce your initial problem either
> If credentials are invalid, no error is shown

**Comment by bestbelief** [comment]
hello, How to add TlS to this library ? IS it  in connentOptions?
 var connectOptions = {
    host: "127.0.0.1",
    port: 8883,
    protocol: "mqtts",
    keepalive: 10,
    clientId: client_id,
    protocolId: "MQTT",
    protocolVersion: 4,
    clean: false,
    //username:"user1",
    //password:"user1",
    /*reconnectPeriod: 2000,
    connectTimeout: 2000,*/

  ** i want to know how can we add following  key and cert in this  library ?**

    key: fs.readFileSync("../certs/user1.key"),  
    cert: fs.readFileSync("../certs/user1.crt"),
    rejectUnauthorized: false,
};

**Comment by sclausen** [comment]
Sorry, but you can't use certificates in the browser.
